// Code generated by clientgen. DO NOT EDIT.

package devices

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Devices provides access to the Devices API.
type Devices struct {
	client *http.Client
}

// NewDevices creates a new Devices instance.
func NewDevices(client *http.Client) *Devices {
	return &Devices{
		client: client,
	}
}

// ExecuteAdoptedDeviceAction calls the ExecuteAdoptedDeviceAction endpoint.
// POST /v1/sites/{siteId}/devices/{deviceId}/actions
func (c *Devices) ExecuteAdoptedDeviceAction(ctx context.Context, siteId string, deviceId string, req *ExecuteAdoptedDeviceActionRequest) (*ExecuteAdoptedDeviceActionResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/devices/%s/actions", siteId, deviceId)
	var result ExecuteAdoptedDeviceActionResponse
	if err := c.client.Post(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetAdoptedDeviceDetails calls the GetAdoptedDeviceDetails endpoint.
// GET /v1/sites/{siteId}/devices/{deviceId}
func (c *Devices) GetAdoptedDeviceDetails(ctx context.Context, siteId string, deviceId string) (*GetAdoptedDeviceDetailsResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/devices/%s", siteId, deviceId)
	var result GetAdoptedDeviceDetailsResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListAdoptedDevices calls the ListAdoptedDevices endpoint.
// GET /v1/sites/{siteId}/devices
func (c *Devices) ListAdoptedDevices(ctx context.Context, siteId string) (*ListAdoptedDevicesResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/devices", siteId)
	var result ListAdoptedDevicesResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
