// Code generated by typegen. DO NOT EDIT.
// Endpoint: Execute Adopted Device Action
// Method: POST /v1/sites/{siteId}/devices/{deviceId}/actions

package devices

// ExecuteAdoptedDeviceActionPathParams contains the path parameters for the ExecuteAdoptedDeviceAction endpoint.
type ExecuteAdoptedDeviceActionPathParams struct {
	SiteId   string `json:"siteId"`
	DeviceId string `json:"deviceId"`
}

// ExecuteAdoptedDeviceActionRequest contains the request body for the ExecuteAdoptedDeviceAction endpoint.
type ExecuteAdoptedDeviceActionRequest struct {
	Action string `json:"action"`
}

// ExecuteAdoptedDeviceActionResponse represents the API response for Execute Adopted Device Action.
type ExecuteAdoptedDeviceActionResponse struct{}

// ExecuteAdoptedDeviceActionAction represents the action enum values.
type ExecuteAdoptedDeviceActionAction string

const (
	ExecuteAdoptedDeviceActionActionRestart ExecuteAdoptedDeviceActionAction = "RESTART"
)
