// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Adopted Device Details
// Method: GET /v1/sites/{siteId}/devices/{deviceId}

package devices

import (
	"encoding/json"
	"time"
)

// GetAdoptedDeviceDetailsPathParams contains the path parameters for the GetAdoptedDeviceDetails endpoint.
type GetAdoptedDeviceDetailsPathParams struct {
	SiteId   string `json:"siteId"`
	DeviceId string `json:"deviceId"`
}

// GetAdoptedDeviceDetailsResponse contains the response body from the GetAdoptedDeviceDetails endpoint.
type GetAdoptedDeviceDetailsResponse struct {
	Id                string     `json:"id"`
	MacAddress        string     `json:"macAddress"`
	IpAddress         string     `json:"ipAddress"`
	Name              string     `json:"name"`
	Model             string     `json:"model"`
	Supported         bool       `json:"supported"`
	State             string     `json:"state"`
	FirmwareVersion   string     `json:"firmwareVersion,omitempty"`
	FirmwareUpdatable bool       `json:"firmwareUpdatable"`
	AdoptedAt         *time.Time `json:"adoptedAt,omitempty"`
	ProvisionedAt     *time.Time `json:"provisionedAt,omitempty"`
	ConfigurationId   string     `json:"configurationId"`
	// Uplink interface is device's connection to the parent device in the network t...
	Uplink     *GetAdoptedDeviceDetailsUplink     `json:"uplink,omitempty"`
	Features   *GetAdoptedDeviceDetailsFeatures   `json:"features"`
	Interfaces *GetAdoptedDeviceDetailsInterfaces `json:"interfaces"`
}

// GetAdoptedDeviceDetailsInterfaces represents a nested object structure.
type GetAdoptedDeviceDetailsInterfaces struct {
	Ports  []GetAdoptedDeviceDetailsInterfacesPorts  `json:"ports,omitempty"`
	Radios []GetAdoptedDeviceDetailsInterfacesRadios `json:"radios,omitempty"`
}

// GetAdoptedDeviceDetailsUplink represents a nested object structure.
type GetAdoptedDeviceDetailsUplink struct {
	DeviceId string `json:"deviceId"`
}

// GetAdoptedDeviceDetailsFeatures represents a nested object structure.
type GetAdoptedDeviceDetailsFeatures struct {
	Switching   json.RawMessage `json:"switching,omitempty"`
	AccessPoint json.RawMessage `json:"accessPoint,omitempty"`
}

// GetAdoptedDeviceDetailsInterfacesPorts represents a nested object structure.
type GetAdoptedDeviceDetailsInterfacesPorts struct {
	Idx          int64                                      `json:"idx"`
	State        string                                     `json:"state"`
	Connector    string                                     `json:"connector"`
	MaxSpeedMbps int64                                      `json:"maxSpeedMbps"`
	SpeedMbps    int64                                      `json:"speedMbps,omitempty"`
	Poe          *GetAdoptedDeviceDetailsInterfacesPortsPoe `json:"poe,omitempty"`
}

// GetAdoptedDeviceDetailsInterfacesPortsPoe represents a nested object structure.
type GetAdoptedDeviceDetailsInterfacesPortsPoe struct {
	Standard string `json:"standard"`
	Type     int64  `json:"type"`
	// Whether the PoE feature is enabled on the port
	Enabled bool `json:"enabled"`
	// Whether the port currently supplies power to the (connected) device.
	State string `json:"state"`
}

// GetAdoptedDeviceDetailsInterfacesRadios represents a nested object structure.
type GetAdoptedDeviceDetailsInterfacesRadios struct {
	WlanStandard    string  `json:"wlanStandard"`
	FrequencyGHz    float64 `json:"frequencyGHz"`
	ChannelWidthMHz int64   `json:"channelWidthMHz"`
	Channel         int64   `json:"channel,omitempty"`
}
