// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Adopted Devices
// Method: GET /v1/sites/{siteId}/devices

package devices

import (
	"encoding/json"
)

// ListAdoptedDevicesPathParams contains the path parameters for the ListAdoptedDevices endpoint.
type ListAdoptedDevicesPathParams struct {
	SiteId string `json:"siteId"`
}

// ListAdoptedDevicesResponse contains the response body from the ListAdoptedDevices endpoint.
type ListAdoptedDevicesResponse struct {
	PaginatedResponse
	Data []ListAdoptedDevicesData `json:"data"`
}

// ListAdoptedDevicesData represents a nested object structure.
type ListAdoptedDevicesData struct {
	Id                string            `json:"id"`
	MacAddress        string            `json:"macAddress"`
	IpAddress         string            `json:"ipAddress"`
	Name              string            `json:"name"`
	Model             string            `json:"model"`
	State             string            `json:"state"`
	Supported         bool              `json:"supported"`
	FirmwareVersion   string            `json:"firmwareVersion,omitempty"`
	FirmwareUpdatable bool              `json:"firmwareUpdatable"`
	Features          []json.RawMessage `json:"features"`
	Interfaces        []json.RawMessage `json:"interfaces"`
}
