// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Local Sites
// Method: GET /v1/sites

package sites

// ListLocalSitesResponse contains the response body from the ListLocalSites endpoint.
type ListLocalSitesResponse struct {
	PaginatedResponse
	Data []Site `json:"data"`
}
