// Code generated by clientgen. DO NOT EDIT.

package sites

import (
	"context"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Sites provides access to the Sites API.
type Sites struct {
	client *http.Client
}

// NewSites creates a new Sites instance.
func NewSites(client *http.Client) *Sites {
	return &Sites{
		client: client,
	}
}

// ListLocalSites calls the ListLocalSites endpoint.
// GET /v1/sites
func (c *Sites) ListLocalSites(ctx context.Context) (*ListLocalSitesResponse, error) {
	path := "/v1/sites"
	var result ListLocalSitesResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
