// Code generated by typegen. DO NOT EDIT.
// Endpoint: Delete Vouchers
// Method: DELETE /v1/sites/{siteId}/hotspot/vouchers

package network

// DeleteVouchersPathParams contains the path parameters for the DeleteVouchers endpoint.
type DeleteVouchersPathParams struct {
	SiteId string `json:"siteId"`
}

// DeleteVouchersResponse contains the response body from the DeleteVouchers endpoint.
type DeleteVouchersResponse struct {
	VouchersDeleted int64 `json:"vouchersDeleted,omitempty"`
}

