// Code generated by typegen. DO NOT EDIT.
// Endpoint: Execute Device Action
// Method: POST /v1/sites/{siteId}/devices/{deviceId}/actions

package network

// ExecuteDeviceActionPathParams contains the path parameters for the ExecuteDeviceAction endpoint.
type ExecuteDeviceActionPathParams struct {
	SiteId string `json:"siteId"`
	DeviceId string `json:"deviceId"`
}

// ExecuteDeviceActionRequest contains the request body for the ExecuteDeviceAction endpoint.
type ExecuteDeviceActionRequest struct {
	Action string `json:"action"`
}

// ExecuteDeviceActionAction represents the action enum values.
type ExecuteDeviceActionAction string

const (
	ExecuteDeviceActionActionRestart ExecuteDeviceActionAction = "RESTART"
)

