// Code generated by typegen. DO NOT EDIT.
// Endpoint: Execute Port Action
// Method: POST /v1/sites/{siteId}/devices/{deviceId}/interfaces/ports/{portIdx}/actions

package network

// ExecutePortActionPathParams contains the path parameters for the ExecutePortAction endpoint.
type ExecutePortActionPathParams struct {
	PortIdx int64 `json:"portIdx"`
	SiteId string `json:"siteId"`
	DeviceId string `json:"deviceId"`
}

// ExecutePortActionRequest contains the request body for the ExecutePortAction endpoint.
type ExecutePortActionRequest struct {
	Action string `json:"action"`
}

// ExecutePortActionAction represents the action enum values.
type ExecutePortActionAction string

const (
	ExecutePortActionActionPowerCycle ExecutePortActionAction = "POWER_CYCLE"
)

