// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Latest Device Statistics
// Method: GET /v1/sites/{siteId}/devices/{deviceId}/statistics/latest

package network

import (
	"time"
)

// GetLatestDeviceStatisticsPathParams contains the path parameters for the GetLatestDeviceStatistics endpoint.
type GetLatestDeviceStatisticsPathParams struct {
	SiteId string `json:"siteId"`
	DeviceId string `json:"deviceId"`
}

// GetLatestDeviceStatisticsResponse contains the response body from the GetLatestDeviceStatistics endpoint.
type GetLatestDeviceStatisticsResponse struct {
	UptimeSec int64 `json:"uptimeSec,omitempty"`
	LastHeartbeatAt *time.Time `json:"lastHeartbeatAt,omitempty"`
	NextHeartbeatAt *time.Time `json:"nextHeartbeatAt,omitempty"`
	LoadAverage1Min float64 `json:"loadAverage1Min,omitempty"`
	LoadAverage5Min float64 `json:"loadAverage5Min,omitempty"`
	LoadAverage15Min float64 `json:"loadAverage15Min,omitempty"`
	CpuUtilizationPct float64 `json:"cpuUtilizationPct,omitempty"`
	MemoryUtilizationPct float64 `json:"memoryUtilizationPct,omitempty"`
	Uplink *GetLatestDeviceStatisticsUplink `json:"uplink,omitempty"`
	Interfaces *GetLatestDeviceStatisticsInterfaces `json:"interfaces"`
}

// GetLatestDeviceStatisticsUplink represents a nested object structure.
type GetLatestDeviceStatisticsUplink struct {
	TxRateBps int64 `json:"txRateBps,omitempty"`
	RxRateBps int64 `json:"rxRateBps,omitempty"`
}

// GetLatestDeviceStatisticsInterfaces represents a nested object structure.
type GetLatestDeviceStatisticsInterfaces struct {
	Radios []GetLatestDeviceStatisticsInterfacesRadios `json:"radios,omitempty"`
}

// GetLatestDeviceStatisticsInterfacesRadios represents a nested object structure.
type GetLatestDeviceStatisticsInterfacesRadios struct {
	FrequencyGHz float64 `json:"frequencyGHz"`
	TxRetriesPct float64 `json:"txRetriesPct,omitempty"`
}

