// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Application Info
// Method: GET /v1/info

package network

// GetApplicationInfoResponse contains the response body from the GetApplicationInfo endpoint.
type GetApplicationInfoResponse struct {
	ApplicationVersion string `json:"applicationVersion"`
}

