// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Device Details
// Method: GET /v1/sites/{siteId}/devices/{deviceId}

package network

import (
	"encoding/json"
	"time"
)

// GetDeviceDetailsPathParams contains the path parameters for the GetDeviceDetails endpoint.
type GetDeviceDetailsPathParams struct {
	SiteId string `json:"siteId"`
	DeviceId string `json:"deviceId"`
}

// GetDeviceDetailsResponse contains the response body from the GetDeviceDetails endpoint.
type GetDeviceDetailsResponse struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Model string `json:"model"`
	Supported bool `json:"supported"`
	MacAddress string `json:"macAddress"`
	IpAddress string `json:"ipAddress"`
	State string `json:"state"`
	FirmwareVersion string `json:"firmwareVersion,omitempty"`
	FirmwareUpdatable bool `json:"firmwareUpdatable"`
	AdoptedAt *time.Time `json:"adoptedAt,omitempty"`
	ProvisionedAt *time.Time `json:"provisionedAt,omitempty"`
	ConfigurationId string `json:"configurationId"`
	// Uplink interface is device's connection to the parent device in the network t...
	Uplink *GetDeviceDetailsUplink `json:"uplink,omitempty"`
	Features *GetDeviceDetailsFeatures `json:"features"`
	Interfaces *GetDeviceDetailsInterfaces `json:"interfaces"`
}

// GetDeviceDetailsUplink represents a nested object structure.
type GetDeviceDetailsUplink struct {
	DeviceId string `json:"deviceId"`
}

// GetDeviceDetailsInterfacesRadios represents a nested object structure.
type GetDeviceDetailsInterfacesRadios struct {
	WlanStandard string `json:"wlanStandard"`
	FrequencyGHz float64 `json:"frequencyGHz"`
	ChannelWidthMHz int64 `json:"channelWidthMHz"`
	Channel int64 `json:"channel,omitempty"`
}

// GetDeviceDetailsInterfaces represents a nested object structure.
type GetDeviceDetailsInterfaces struct {
	Ports []GetDeviceDetailsInterfacesPorts `json:"ports,omitempty"`
	Radios []GetDeviceDetailsInterfacesRadios `json:"radios,omitempty"`
}

// GetDeviceDetailsFeatures represents a nested object structure.
type GetDeviceDetailsFeatures struct {
	Switching json.RawMessage `json:"switching,omitempty"`
	AccessPoint json.RawMessage `json:"accessPoint,omitempty"`
}

// GetDeviceDetailsInterfacesPorts represents a nested object structure.
type GetDeviceDetailsInterfacesPorts struct {
	Idx int64 `json:"idx"`
	State string `json:"state"`
	Connector string `json:"connector"`
	MaxSpeedMbps int64 `json:"maxSpeedMbps"`
	SpeedMbps int64 `json:"speedMbps,omitempty"`
	Poe *GetDeviceDetailsInterfacesPortsPoe `json:"poe,omitempty"`
}

// GetDeviceDetailsInterfacesPortsPoe represents a nested object structure.
type GetDeviceDetailsInterfacesPortsPoe struct {
	Standard string `json:"standard"`
	Type int64 `json:"type"`
	// Whether the PoE feature is enabled on the port
	Enabled bool `json:"enabled"`
	// Whether the port currently supplies power to the (connected) device.
	State string `json:"state"`
}

