// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Devices
// Method: GET /v1/sites/{siteId}/devices

package network

import (
	"encoding/json"
)

// ListDevicesPathParams contains the path parameters for the ListDevices endpoint.
type ListDevicesPathParams struct {
	SiteId string `json:"siteId"`
}

// ListDevicesResponse contains the response body from the ListDevices endpoint.
type ListDevicesResponse struct {
	PaginatedResponse
	Data []ListDevicesData `json:"data"`
}

// ListDevicesData represents a nested object structure.
type ListDevicesData struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Model string `json:"model"`
	MacAddress string `json:"macAddress"`
	IpAddress string `json:"ipAddress"`
	State string `json:"state"`
	Features []json.RawMessage `json:"features"`
	Interfaces []json.RawMessage `json:"interfaces"`
}

