// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Connected Clients
// Method: GET /v1/sites/{siteId}/clients

package network

// ListConnectedClientsPathParams contains the path parameters for the ListConnectedClients endpoint.
type ListConnectedClientsPathParams struct {
	SiteId string `json:"siteId"`
}

// ListConnectedClientsResponse contains the response body from the ListConnectedClients endpoint.
type ListConnectedClientsResponse struct {
	PaginatedResponse
	Data []Client `json:"data"`
}

