package clientgen

// clientTemplateStr is the template for generating a complete client file.
const clientTemplateStr = `// Code generated by clientgen. DO NOT EDIT.

package {{.PackageName}}

import (
	"context"
{{- if .NeedsFmt}}
	"fmt"
{{- end}}

	"github.com/ilmax/unifi-client-go/internal/http"
)

// {{.ClientName}} provides access to the {{.ClientName}} API.
type {{.ClientName}} struct {
	client *http.Client
}

// New{{.ClientName}} creates a new {{.ClientName}} instance.
func New{{.ClientName}}(client *http.Client) *{{.ClientName}} {
	return &{{.ClientName}}{
		client: client,
	}
}
{{range .Methods}}
// {{.Name}} {{if .Description}}{{.Description}}{{else}}calls the {{.EndpointName}} endpoint.{{end}}
// {{.HTTPMethod}} {{.Path}}
func (c *{{$.ClientName}}) {{.Name}}(ctx context.Context{{range .PathParams}}, {{. | toCamelCase}} string{{end}}{{if .HasRequestBody}}, req {{.RequestParam}}{{end}}) ({{.ResponseParam}}, error) {
{{- if .PathParams}}
	path := fmt.Sprintf("{{formatPath .PathParams .Path}}"{{range .PathParams}}, {{. | toCamelCase}}{{end}})
{{- else}}
	path := "{{.Path}}"
{{- end}}
	var result {{.ResponseVar}}
{{- if eq .HTTPMethod "GET"}}
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
{{- else if eq .HTTPMethod "POST"}}
	if err := c.client.Post(ctx, path, req, &result); err != nil {
		return nil, err
	}
{{- else if eq .HTTPMethod "PUT"}}
	if err := c.client.Put(ctx, path, req, &result); err != nil {
		return nil, err
	}
{{- else if eq .HTTPMethod "DELETE"}}
	if err := c.client.Delete(ctx, path, &result); err != nil {
		return nil, err
	}
{{- end}}
	return {{if eq .ResponseParam "any"}}result{{else}}&result{{end}}, nil
}
{{end}}`

// methodTemplateStr is the template for generating a single client method.
// This is used when generating methods individually.
const methodTemplateStr = `// {{.Name}} {{if .Description}}{{.Description}}{{else}}calls the {{.EndpointName}} endpoint.{{end}}
// {{.HTTPMethod}} {{.Path}}
func (c *Client) {{.Name}}(ctx context.Context{{range .PathParams}}, {{. | toCamelCase}} string{{end}}{{if .HasRequestBody}}, req {{.RequestParam}}{{end}}) ({{.ResponseParam}}, error) {
{{- if .PathParams}}
	path := fmt.Sprintf("{{formatPath .PathParams .Path}}"{{range .PathParams}}, {{. | toCamelCase}}{{end}})
{{- else}}
	path := "{{.Path}}"
{{- end}}
	var result {{.ResponseVar}}
{{- if eq .HTTPMethod "GET"}}
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
{{- else if eq .HTTPMethod "POST"}}
	if err := c.client.Post(ctx, path, req, &result); err != nil {
		return nil, err
	}
{{- else if eq .HTTPMethod "PUT"}}
	if err := c.client.Put(ctx, path, req, &result); err != nil {
		return nil, err
	}
{{- else if eq .HTTPMethod "DELETE"}}
	if err := c.client.Delete(ctx, path, &result); err != nil {
		return nil, err
	}
{{- end}}
	return {{if eq .ResponseParam "any"}}result{{else}}&result{{end}}, nil
}
`
