// Code generated by clientgen. DO NOT EDIT.

package ports

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Ports provides access to the Ports API.
type Ports struct {
	client *http.Client
}

// NewPorts creates a new Ports instance.
func NewPorts(client *http.Client) *Ports {
	return &Ports{
		client: client,
	}
}

// ExecutePortAction calls the ExecutePortAction endpoint.
// POST /v1/sites/{siteId}/devices/{deviceId}/interfaces/ports/{portIdx}/actions
func (c *Ports) ExecutePortAction(ctx context.Context, portIdx string, siteId string, deviceId string, req *ExecutePortActionRequest) (*ExecutePortActionResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/devices/%s/interfaces/ports/%s/actions", portIdx, siteId, deviceId)
	var result ExecutePortActionResponse
	if err := c.client.Post(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
