// Code generated by typegen. DO NOT EDIT.
// Endpoint: Delete Voucher
// Method: DELETE /v1/sites/{siteId}/hotspot/vouchers/{voucherId}

package vouchers

// DeleteVoucherPathParams contains the path parameters for the DeleteVoucher endpoint.
type DeleteVoucherPathParams struct {
	VoucherId string `json:"voucherId"`
	SiteId    string `json:"siteId"`
}

// DeleteVoucherResponse contains the response body from the DeleteVoucher endpoint.
type DeleteVoucherResponse struct {
	VouchersDeleted int64 `json:"vouchersDeleted,omitempty"`
}
