// Code generated by typegen. DO NOT EDIT.
// Endpoint: Generate Vouchers
// Method: POST /v1/sites/{siteId}/hotspot/vouchers

package vouchers

// GenerateVouchersPathParams contains the path parameters for the GenerateVouchers endpoint.
type GenerateVouchersPathParams struct {
	SiteId string `json:"siteId"`
}

// GenerateVouchersRequest contains the request body for the GenerateVouchers endpoint.
type GenerateVouchersRequest struct {
	// Number of vouchers to generate
	Count int64 `json:"count,omitempty"`
	// Voucher note, duplicated across all generated vouchers
	Name string `json:"name"`
	// (Optional) limit for how many different guests can use the same voucher to au...
	AuthorizedGuestLimit int64 `json:"authorizedGuestLimit,omitempty"`
	// How long (in minutes) the voucher will provide access to the network since au...
	TimeLimitMinutes int64 `json:"timeLimitMinutes"`
	// (Optional) data usage limit in megabytes
	DataUsageLimitMBytes int64 `json:"dataUsageLimitMBytes,omitempty"`
	// (Optional) download rate limit in kilobits per second
	RxRateLimitKbps int64 `json:"rxRateLimitKbps,omitempty"`
	// (Optional) upload rate limit in kilobits per second
	TxRateLimitKbps int64 `json:"txRateLimitKbps,omitempty"`
}

// GenerateVouchersResponse contains the response body from the GenerateVouchers endpoint.
type GenerateVouchersResponse struct {
	Vouchers []Voucher `json:"vouchers,omitempty"`
}
