// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Voucher Details
// Method: GET /v1/sites/{siteId}/hotspot/vouchers/{voucherId}

package vouchers

// GetVoucherDetailsPathParams contains the path parameters for the GetVoucherDetails endpoint.
type GetVoucherDetailsPathParams struct {
	VoucherId string `json:"voucherId"`
	SiteId    string `json:"siteId"`
}

// GetVoucherDetailsResponse is an alias for Voucher.
type GetVoucherDetailsResponse = Voucher
