// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Vouchers
// Method: GET /v1/sites/{siteId}/hotspot/vouchers

package vouchers

// ListVouchersPathParams contains the path parameters for the ListVouchers endpoint.
type ListVouchersPathParams struct {
	SiteId string `json:"siteId"`
}

// ListVouchersResponse contains the response body from the ListVouchers endpoint.
type ListVouchersResponse struct {
	PaginatedResponse
	Data []Voucher `json:"data"`
}
