// Code generated by clientgen. DO NOT EDIT.

package vouchers

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Vouchers provides access to the Vouchers API.
type Vouchers struct {
	client *http.Client
}

// NewVouchers creates a new Vouchers instance.
func NewVouchers(client *http.Client) *Vouchers {
	return &Vouchers{
		client: client,
	}
}

// DeleteVoucher calls the DeleteVoucher endpoint.
// DELETE /v1/sites/{siteId}/hotspot/vouchers/{voucherId}
func (c *Vouchers) DeleteVoucher(ctx context.Context, voucherId string, siteId string) (*DeleteVoucherResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/hotspot/vouchers/%s", voucherId, siteId)
	var result DeleteVoucherResponse
	if err := c.client.Delete(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteVouchers calls the DeleteVouchers endpoint.
// DELETE /v1/sites/{siteId}/hotspot/vouchers
func (c *Vouchers) DeleteVouchers(ctx context.Context, siteId string) (*DeleteVouchersResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/hotspot/vouchers", siteId)
	var result DeleteVouchersResponse
	if err := c.client.Delete(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateGenerateVouchers calls the GenerateVouchers endpoint.
// POST /v1/sites/{siteId}/hotspot/vouchers
func (c *Vouchers) CreateGenerateVouchers(ctx context.Context, siteId string, req *GenerateVouchersRequest) (*GenerateVouchersResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/hotspot/vouchers", siteId)
	var result GenerateVouchersResponse
	if err := c.client.Post(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetVoucherDetails calls the GetVoucherDetails endpoint.
// GET /v1/sites/{siteId}/hotspot/vouchers/{voucherId}
func (c *Vouchers) GetVoucherDetails(ctx context.Context, voucherId string, siteId string) (*GetVoucherDetailsResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/hotspot/vouchers/%s", voucherId, siteId)
	var result GetVoucherDetailsResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListVouchers calls the ListVouchers endpoint.
// GET /v1/sites/{siteId}/hotspot/vouchers
func (c *Vouchers) ListVouchers(ctx context.Context, siteId string) (*ListVouchersResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/hotspot/vouchers", siteId)
	var result ListVouchersResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
