// Code generated by typegen. DO NOT EDIT.
// Endpoint: List WAN Interfaces
// Method: GET /v1/sites/{siteId}/wans

package wans

// ListWANInterfacesPathParams contains the path parameters for the ListWANInterfaces endpoint.
type ListWANInterfacesPathParams struct {
	SiteId string `json:"siteId"`
}

// ListWANInterfacesResponse contains the response body from the ListWANInterfaces endpoint.
type ListWANInterfacesResponse struct {
	PaginatedResponse
	Data []ListWANInterfacesData `json:"data"`
}

// ListWANInterfacesData represents a nested object structure.
type ListWANInterfacesData struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
