// Code generated by clientgen. DO NOT EDIT.

package wans

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Wans provides access to the Wans API.
type Wans struct {
	client *http.Client
}

// NewWans creates a new Wans instance.
func NewWans(client *http.Client) *Wans {
	return &Wans{
		client: client,
	}
}

// ListWANInterfaces calls the ListWANInterfaces endpoint.
// GET /v1/sites/{siteId}/wans
func (c *Wans) ListWANInterfaces(ctx context.Context, siteId string) (*ListWANInterfacesResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/wans", siteId)
	var result ListWANInterfacesResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
