// Code generated by clientgen. DO NOT EDIT.

package categories

import (
	"context"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Categories provides access to the Categories API.
type Categories struct {
	client *http.Client
}

// NewCategories creates a new Categories instance.
func NewCategories(client *http.Client) *Categories {
	return &Categories{
		client: client,
	}
}

// ListDPICategories calls the ListDPICategories endpoint.
// GET /v1/dpi/categories
func (c *Categories) ListDPICategories(ctx context.Context) (*ListDPICategoriesResponse, error) {
	path := "/v1/dpi/categories"
	var result ListDPICategoriesResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
