// Code generated by typegen. DO NOT EDIT.
// Common types shared across multiple endpoints.

package categories

import (
	"encoding/json"
	"time"
)

// PaginatedResponse contains pagination metadata for list endpoints.
type PaginatedResponse struct {
	Offset     int64 `json:"offset"`
	Limit      int64 `json:"limit"`
	Count      int64 `json:"count"`
	TotalCount int64 `json:"totalCount"`
}

// Voucher represents a hotspot voucher.
type Voucher struct {
	Id                   string     `json:"id"`
	CreatedAt            time.Time  `json:"createdAt"`
	Name                 string     `json:"name"`
	Code                 string     `json:"code"`
	AuthorizedGuestLimit int64      `json:"authorizedGuestLimit,omitempty"`
	AuthorizedGuestCount int64      `json:"authorizedGuestCount"`
	ActivatedAt          *time.Time `json:"activatedAt,omitempty"`
	ExpiresAt            *time.Time `json:"expiresAt,omitempty"`
	Expired              bool       `json:"expired"`
	TimeLimitMinutes     int64      `json:"timeLimitMinutes"`
	DataUsageLimitMBytes int64      `json:"dataUsageLimitMBytes,omitempty"`
	RxRateLimitKbps      int64      `json:"rxRateLimitKbps,omitempty"`
	TxRateLimitKbps      int64      `json:"txRateLimitKbps,omitempty"`
}

// Client represents a connected network client.
type Client struct {
	Id             string        `json:"id"`
	Name           string        `json:"name"`
	ConnectedAt    *time.Time    `json:"connectedAt,omitempty"`
	IpAddress      string        `json:"ipAddress,omitempty"`
	Access         *ClientAccess `json:"access"`
	Type           string        `json:"type"`
	MacAddress     string        `json:"macAddress,omitempty"`
	UplinkDeviceId string        `json:"uplinkDeviceId,omitempty"`
}

// ClientAccess represents the network access type and authorization status.
type ClientAccess struct {
	Type string `json:"type"`
}

// Authorization represents a guest authorization.
type Authorization struct {
	AuthorizedAt         time.Time           `json:"authorizedAt"`
	AuthorizationMethod  string              `json:"authorizationMethod"`
	ExpiresAt            time.Time           `json:"expiresAt"`
	DataUsageLimitMBytes int64               `json:"dataUsageLimitMBytes,omitempty"`
	RxRateLimitKbps      int64               `json:"rxRateLimitKbps,omitempty"`
	TxRateLimitKbps      int64               `json:"txRateLimitKbps,omitempty"`
	Usage                *AuthorizationUsage `json:"usage,omitempty"`
}

// AuthorizationUsage represents usage statistics for an authorization.
type AuthorizationUsage struct {
	DurationSec int64 `json:"durationSec"`
	RxBytes     int64 `json:"rxBytes"`
	TxBytes     int64 `json:"txBytes"`
	Bytes       int64 `json:"bytes"`
}

// Site represents a UniFi site.
type Site struct {
	Id                string `json:"id"`
	InternalReference string `json:"internalReference"`
	Name              string `json:"name"`
}

// Device represents an adopted UniFi device.
type Device struct {
	Id                string            `json:"id"`
	Name              string            `json:"name"`
	Model             string            `json:"model"`
	MacAddress        string            `json:"macAddress"`
	IpAddress         string            `json:"ipAddress"`
	State             string            `json:"state"`
	Supported         bool              `json:"supported,omitempty"`
	FirmwareVersion   string            `json:"firmwareVersion,omitempty"`
	FirmwareUpdatable bool              `json:"firmwareUpdatable,omitempty"`
	AdoptedAt         *time.Time        `json:"adoptedAt,omitempty"`
	ProvisionedAt     *time.Time        `json:"provisionedAt,omitempty"`
	ConfigurationId   string            `json:"configurationId,omitempty"`
	Uplink            *DeviceUplink     `json:"uplink,omitempty"`
	Features          *DeviceFeatures   `json:"features,omitempty"`
	Interfaces        *DeviceInterfaces `json:"interfaces,omitempty"`
}

// DeviceUplink represents the device's uplink connection.
type DeviceUplink struct {
	DeviceId  string `json:"deviceId"`
	TxRateBps int64  `json:"txRateBps,omitempty"`
	RxRateBps int64  `json:"rxRateBps,omitempty"`
}

// DeviceFeatures represents device feature capabilities.
type DeviceFeatures struct {
	Switching   json.RawMessage `json:"switching,omitempty"`
	AccessPoint json.RawMessage `json:"accessPoint,omitempty"`
}

// DeviceInterfaces represents device network interfaces.
type DeviceInterfaces struct {
	Ports  []DevicePort  `json:"ports,omitempty"`
	Radios []DeviceRadio `json:"radios,omitempty"`
}

// DevicePort represents a network port on a device.
type DevicePort struct {
	Idx          int64      `json:"idx"`
	State        string     `json:"state"`
	Connector    string     `json:"connector"`
	MaxSpeedMbps int64      `json:"maxSpeedMbps"`
	SpeedMbps    int64      `json:"speedMbps,omitempty"`
	Poe          *DevicePoe `json:"poe,omitempty"`
}

// DevicePoe represents PoE configuration for a port.
type DevicePoe struct {
	Standard string `json:"standard"`
	Type     int64  `json:"type"`
	Enabled  bool   `json:"enabled"`
	State    string `json:"state"`
}

// DeviceRadio represents a wireless radio interface.
type DeviceRadio struct {
	WlanStandard    string  `json:"wlanStandard"`
	FrequencyGHz    float64 `json:"frequencyGHz"`
	ChannelWidthMHz int64   `json:"channelWidthMHz"`
	Channel         int64   `json:"channel,omitempty"`
	TxRetriesPct    float64 `json:"txRetriesPct,omitempty"`
}

// DeviceStatistics represents device runtime statistics.
type DeviceStatistics struct {
	UptimeSec            int64      `json:"uptimeSec,omitempty"`
	LastHeartbeatAt      *time.Time `json:"lastHeartbeatAt,omitempty"`
	NextHeartbeatAt      *time.Time `json:"nextHeartbeatAt,omitempty"`
	LoadAverage1Min      float64    `json:"loadAverage1Min,omitempty"`
	LoadAverage5Min      float64    `json:"loadAverage5Min,omitempty"`
	LoadAverage15Min     float64    `json:"loadAverage15Min,omitempty"`
	CpuUtilizationPct    float64    `json:"cpuUtilizationPct,omitempty"`
	MemoryUtilizationPct float64    `json:"memoryUtilizationPct,omitempty"`
}
