// Code generated by typegen. DO NOT EDIT.
// Endpoint: List DPI Categories
// Method: GET /v1/dpi/categories

package categories

// ListDPICategoriesResponse contains the response body from the ListDPICategories endpoint.
type ListDPICategoriesResponse struct {
	PaginatedResponse
	Data []ListDPICategoriesData `json:"data"`
}

// ListDPICategoriesData represents a nested object structure.
type ListDPICategoriesData struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}
