// Code generated by typegen. DO NOT EDIT.
// Endpoint: Create Custom Firewall Zone
// Method: POST /v1/sites/{siteId}/firewall/zones

package zones

import (
	"encoding/json"
)

// CreateCustomFirewallZonePathParams contains the path parameters for the CreateCustomFirewallZone endpoint.
type CreateCustomFirewallZonePathParams struct {
	SiteId string `json:"siteId"`
}

// CreateCustomFirewallZoneRequest contains the request body for the CreateCustomFirewallZone endpoint.
type CreateCustomFirewallZoneRequest struct {
	// Name of a firewall zone
	Name string `json:"name"`
	// List of Network IDs
	NetworkIds []json.RawMessage `json:"networkIds"`
}

// CreateCustomFirewallZoneResponse contains the response body from the CreateCustomFirewallZone endpoint.
type CreateCustomFirewallZoneResponse struct {
	Id string `json:"id"`
	// Name of a firewall zone
	Name string `json:"name"`
	// List of Network IDs
	NetworkIds []json.RawMessage `json:"networkIds"`
	// System-defined configurable zones support configuring only attached networks
	Metadata *CreateCustomFirewallZoneMetadata `json:"metadata"`
}

// CreateCustomFirewallZoneMetadata represents a nested object structure.
type CreateCustomFirewallZoneMetadata struct {
	Origin string `json:"origin"`
}
