// Code generated by typegen. DO NOT EDIT.
// Endpoint: Delete Custom Firewall Zone
// Method: DELETE /v1/sites/{siteId}/firewall/zones/{firewallZoneId}

package zones

// DeleteCustomFirewallZonePathParams contains the path parameters for the DeleteCustomFirewallZone endpoint.
type DeleteCustomFirewallZonePathParams struct {
	FirewallZoneId string `json:"firewallZoneId"`
	SiteId         string `json:"siteId"`
}

// DeleteCustomFirewallZoneResponse represents the API response for Delete Custom Firewall Zone.
type DeleteCustomFirewallZoneResponse struct{}
