// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Firewall Zone
// Method: GET /v1/sites/{siteId}/firewall/zones/{firewallZoneId}

package zones

import (
	"encoding/json"
)

// GetFirewallZonePathParams contains the path parameters for the GetFirewallZone endpoint.
type GetFirewallZonePathParams struct {
	FirewallZoneId string `json:"firewallZoneId"`
	SiteId         string `json:"siteId"`
}

// GetFirewallZoneResponse contains the response body from the GetFirewallZone endpoint.
type GetFirewallZoneResponse struct {
	Id string `json:"id"`
	// Name of a firewall zone
	Name string `json:"name"`
	// List of Network IDs
	NetworkIds []json.RawMessage `json:"networkIds"`
	// System-defined configurable zones support configuring only attached networks
	Metadata *GetFirewallZoneMetadata `json:"metadata"`
}

// GetFirewallZoneMetadata represents a nested object structure.
type GetFirewallZoneMetadata struct {
	Origin string `json:"origin"`
}
