// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Firewall Zones
// Method: GET /v1/sites/{siteId}/firewall/zones

package zones

import (
	"encoding/json"
)

// ListFirewallZonesPathParams contains the path parameters for the ListFirewallZones endpoint.
type ListFirewallZonesPathParams struct {
	SiteId string `json:"siteId"`
}

// ListFirewallZonesResponse contains the response body from the ListFirewallZones endpoint.
type ListFirewallZonesResponse struct {
	PaginatedResponse
	Data []ListFirewallZonesData `json:"data"`
}

// ListFirewallZonesData represents a nested object structure.
type ListFirewallZonesData struct {
	Id string `json:"id"`
	// Name of a firewall zone
	Name string `json:"name"`
	// List of Network IDs
	NetworkIds []json.RawMessage `json:"networkIds"`
	// System-defined configurable zones support configuring only attached networks
	Metadata *ListFirewallZonesDataMetadata `json:"metadata"`
}

// ListFirewallZonesDataMetadata represents a nested object structure.
type ListFirewallZonesDataMetadata struct {
	Origin string `json:"origin"`
}
