// Code generated by typegen. DO NOT EDIT.
// Endpoint: Update Firewall Zone
// Method: PUT /v1/sites/{siteId}/firewall/zones/{firewallZoneId}

package zones

import (
	"encoding/json"
)

// UpdateFirewallZonePathParams contains the path parameters for the UpdateFirewallZone endpoint.
type UpdateFirewallZonePathParams struct {
	FirewallZoneId string `json:"firewallZoneId"`
	SiteId         string `json:"siteId"`
}

// UpdateFirewallZoneRequest contains the request body for the UpdateFirewallZone endpoint.
type UpdateFirewallZoneRequest struct {
	// Name of a firewall zone
	Name string `json:"name"`
	// List of Network IDs
	NetworkIds []json.RawMessage `json:"networkIds"`
}

// UpdateFirewallZoneResponse contains the response body from the UpdateFirewallZone endpoint.
type UpdateFirewallZoneResponse struct {
	Id string `json:"id"`
	// Name of a firewall zone
	Name string `json:"name"`
	// List of Network IDs
	NetworkIds []json.RawMessage `json:"networkIds"`
	// System-defined configurable zones support configuring only attached networks
	Metadata *UpdateFirewallZoneMetadata `json:"metadata"`
}

// UpdateFirewallZoneMetadata represents a nested object structure.
type UpdateFirewallZoneMetadata struct {
	Origin string `json:"origin"`
}
