// Code generated by clientgen. DO NOT EDIT.

package zones

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Zones provides access to the Zones API.
type Zones struct {
	client *http.Client
}

// NewZones creates a new Zones instance.
func NewZones(client *http.Client) *Zones {
	return &Zones{
		client: client,
	}
}

// CreateCustomFirewallZone calls the CreateCustomFirewallZone endpoint.
// POST /v1/sites/{siteId}/firewall/zones
func (c *Zones) CreateCustomFirewallZone(ctx context.Context, siteId string, req *CreateCustomFirewallZoneRequest) (*CreateCustomFirewallZoneResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/firewall/zones", siteId)
	var result CreateCustomFirewallZoneResponse
	if err := c.client.Post(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteCustomFirewallZone calls the DeleteCustomFirewallZone endpoint.
// DELETE /v1/sites/{siteId}/firewall/zones/{firewallZoneId}
func (c *Zones) DeleteCustomFirewallZone(ctx context.Context, firewallZoneId string, siteId string) (*DeleteCustomFirewallZoneResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/firewall/zones/%s", firewallZoneId, siteId)
	var result DeleteCustomFirewallZoneResponse
	if err := c.client.Delete(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetFirewallZone calls the GetFirewallZone endpoint.
// GET /v1/sites/{siteId}/firewall/zones/{firewallZoneId}
func (c *Zones) GetFirewallZone(ctx context.Context, firewallZoneId string, siteId string) (*GetFirewallZoneResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/firewall/zones/%s", firewallZoneId, siteId)
	var result GetFirewallZoneResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListFirewallZones calls the ListFirewallZones endpoint.
// GET /v1/sites/{siteId}/firewall/zones
func (c *Zones) ListFirewallZones(ctx context.Context, siteId string) (*ListFirewallZonesResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/firewall/zones", siteId)
	var result ListFirewallZonesResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateFirewallZone calls the UpdateFirewallZone endpoint.
// PUT /v1/sites/{siteId}/firewall/zones/{firewallZoneId}
func (c *Zones) UpdateFirewallZone(ctx context.Context, firewallZoneId string, siteId string, req *UpdateFirewallZoneRequest) (*UpdateFirewallZoneResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/firewall/zones/%s", firewallZoneId, siteId)
	var result UpdateFirewallZoneResponse
	if err := c.client.Put(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
