// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Latest Adopted Device Statistics
// Method: GET /v1/sites/{siteId}/devices/{deviceId}/statistics/latest

package latest

import (
	"time"
)

// GetLatestAdoptedDeviceStatisticsPathParams contains the path parameters for the GetLatestAdoptedDeviceStatistics endpoint.
type GetLatestAdoptedDeviceStatisticsPathParams struct {
	SiteId   string `json:"siteId"`
	DeviceId string `json:"deviceId"`
}

// GetLatestAdoptedDeviceStatisticsResponse contains the response body from the GetLatestAdoptedDeviceStatistics endpoint.
type GetLatestAdoptedDeviceStatisticsResponse struct {
	UptimeSec            int64                                       `json:"uptimeSec,omitempty"`
	LastHeartbeatAt      *time.Time                                  `json:"lastHeartbeatAt,omitempty"`
	NextHeartbeatAt      *time.Time                                  `json:"nextHeartbeatAt,omitempty"`
	LoadAverage1Min      float64                                     `json:"loadAverage1Min,omitempty"`
	LoadAverage5Min      float64                                     `json:"loadAverage5Min,omitempty"`
	LoadAverage15Min     float64                                     `json:"loadAverage15Min,omitempty"`
	CpuUtilizationPct    float64                                     `json:"cpuUtilizationPct,omitempty"`
	MemoryUtilizationPct float64                                     `json:"memoryUtilizationPct,omitempty"`
	Uplink               *GetLatestAdoptedDeviceStatisticsUplink     `json:"uplink,omitempty"`
	Interfaces           *GetLatestAdoptedDeviceStatisticsInterfaces `json:"interfaces"`
}

// GetLatestAdoptedDeviceStatisticsUplink represents a nested object structure.
type GetLatestAdoptedDeviceStatisticsUplink struct {
	TxRateBps int64 `json:"txRateBps,omitempty"`
	RxRateBps int64 `json:"rxRateBps,omitempty"`
}

// GetLatestAdoptedDeviceStatisticsInterfaces represents a nested object structure.
type GetLatestAdoptedDeviceStatisticsInterfaces struct {
	Radios []GetLatestAdoptedDeviceStatisticsInterfacesRadios `json:"radios,omitempty"`
}

// GetLatestAdoptedDeviceStatisticsInterfacesRadios represents a nested object structure.
type GetLatestAdoptedDeviceStatisticsInterfacesRadios struct {
	FrequencyGHz float64 `json:"frequencyGHz"`
	TxRetriesPct float64 `json:"txRetriesPct,omitempty"`
}
