// Code generated by clientgen. DO NOT EDIT.

package latest

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Latest provides access to the Latest API.
type Latest struct {
	client *http.Client
}

// NewLatest creates a new Latest instance.
func NewLatest(client *http.Client) *Latest {
	return &Latest{
		client: client,
	}
}

// GetLatestAdoptedDeviceStatistics calls the GetLatestAdoptedDeviceStatistics endpoint.
// GET /v1/sites/{siteId}/devices/{deviceId}/statistics/latest
func (c *Latest) GetLatestAdoptedDeviceStatistics(ctx context.Context, siteId string, deviceId string) (*GetLatestAdoptedDeviceStatisticsResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/devices/%s/statistics/latest", siteId, deviceId)
	var result GetLatestAdoptedDeviceStatisticsResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
