// Code generated by clientgen. DO NOT EDIT.

package clients

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Clients provides access to the Clients API.
type Clients struct {
	client *http.Client
}

// NewClients creates a new Clients instance.
func NewClients(client *http.Client) *Clients {
	return &Clients{
		client: client,
	}
}

// ExecuteClientAction calls the ExecuteClientAction endpoint.
// POST /v1/sites/{siteId}/clients/{clientId}/actions
func (c *Clients) ExecuteClientAction(ctx context.Context, clientId string, siteId string, req *ExecuteClientActionRequest) (*ExecuteClientActionResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/clients/%s/actions", clientId, siteId)
	var result ExecuteClientActionResponse
	if err := c.client.Post(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetConnectedClientDetails calls the GetConnectedClientDetails endpoint.
// GET /v1/sites/{siteId}/clients/{clientId}
func (c *Clients) GetConnectedClientDetails(ctx context.Context, clientId string, siteId string) (*GetConnectedClientDetailsResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/clients/%s", clientId, siteId)
	var result GetConnectedClientDetailsResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListConnectedClients calls the ListConnectedClients endpoint.
// GET /v1/sites/{siteId}/clients
func (c *Clients) ListConnectedClients(ctx context.Context, siteId string) (*ListConnectedClientsResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/clients", siteId)
	var result ListConnectedClientsResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
