// Code generated by typegen. DO NOT EDIT.
// Endpoint: Execute Client Action
// Method: POST /v1/sites/{siteId}/clients/{clientId}/actions

package clients

// ExecuteClientActionPathParams contains the path parameters for the ExecuteClientAction endpoint.
type ExecuteClientActionPathParams struct {
	ClientId string `json:"clientId"`
	SiteId   string `json:"siteId"`
}

// ExecuteClientActionRequest contains the request body for the ExecuteClientAction endpoint.
type ExecuteClientActionRequest struct {
	Action string `json:"action"`
	// (Optional) how long (in minutes) the guest will be authorized to access the n...
	TimeLimitMinutes int64 `json:"timeLimitMinutes,omitempty"`
	// (Optional) data usage limit in megabytes
	DataUsageLimitMBytes int64 `json:"dataUsageLimitMBytes,omitempty"`
	// (Optional) download rate limit in kilobits per second
	RxRateLimitKbps int64 `json:"rxRateLimitKbps,omitempty"`
	// (Optional) upload rate limit in kilobits per second
	TxRateLimitKbps int64 `json:"txRateLimitKbps,omitempty"`
}

// ExecuteClientActionResponse contains the response body from the ExecuteClientAction endpoint.
type ExecuteClientActionResponse struct {
	Action string `json:"action"`
	// (Optional) Revoked authorization in case the guest was already authorized at ...
	RevokedAuthorization *Authorization `json:"revokedAuthorization,omitempty"`
	// Granted guest authorization
	GrantedAuthorization *Authorization `json:"grantedAuthorization,omitempty"`
}

// ExecuteClientActionAction represents the action enum values.
type ExecuteClientActionAction string

const (
	ExecuteClientActionActionAuthorizeGuestAccess   ExecuteClientActionAction = "AUTHORIZE_GUEST_ACCESS"
	ExecuteClientActionActionUnauthorizeGuestAccess ExecuteClientActionAction = "UNAUTHORIZE_GUEST_ACCESS"
)
