// Code generated by typegen. DO NOT EDIT.
// Endpoint: Execute Client Action
// Method: POST /v1/sites/{siteId}/clients/{clientId}/actions

package clients

import (
	"encoding/json"
	"fmt"
)

// ExecuteClientActionPathParams contains the path parameters for the ExecuteClientAction endpoint.
type ExecuteClientActionPathParams struct {
	ClientId string `json:"clientId"`
	SiteId   string `json:"siteId"`
}

// ExecuteClientActionRequestAuthorizeGuestAccess represents a nested object structure.
type ExecuteClientActionRequestAuthorizeGuestAccess struct {
	Action string `json:"action"`
	// (Optional) how long (in minutes) the guest will be authorized to access the n...
	TimeLimitMinutes int64 `json:"timeLimitMinutes,omitempty"`
	// (Optional) data usage limit in megabytes
	DataUsageLimitMBytes int64 `json:"dataUsageLimitMBytes,omitempty"`
	// (Optional) download rate limit in kilobits per second
	RxRateLimitKbps int64 `json:"rxRateLimitKbps,omitempty"`
	// (Optional) upload rate limit in kilobits per second
	TxRateLimitKbps int64 `json:"txRateLimitKbps,omitempty"`
}

// ExecuteClientActionRequestUnauthorizeGuestAccess represents a nested object structure.
type ExecuteClientActionRequestUnauthorizeGuestAccess struct {
	Action string `json:"action"`
}

// ExecuteClientActionResponseAuthorizeGuestAccess represents a nested object structure.
type ExecuteClientActionResponseAuthorizeGuestAccess struct {
	Action string `json:"action"`
	// (Optional) Revoked authorization in case the guest was already authorized at ...
	RevokedAuthorization *Authorization `json:"revokedAuthorization,omitempty"`
	// Granted guest authorization
	GrantedAuthorization *Authorization `json:"grantedAuthorization,omitempty"`
}

// ExecuteClientActionResponseUnauthorizeGuestAccess represents a nested object structure.
type ExecuteClientActionResponseUnauthorizeGuestAccess struct {
	Action string `json:"action"`
	// (Optional) Revoked authorization in case the guest was already authorized at ...
	RevokedAuthorization *Authorization `json:"revokedAuthorization,omitempty"`
	// Granted guest authorization
	GrantedAuthorization *Authorization `json:"grantedAuthorization,omitempty"`
}

// ExecuteClientActionAction represents the action enum values.
type ExecuteClientActionAction string

const (
	ExecuteClientActionActionAuthorizeGuestAccess   ExecuteClientActionAction = "AUTHORIZE_GUEST_ACCESS"
	ExecuteClientActionActionUnauthorizeGuestAccess ExecuteClientActionAction = "UNAUTHORIZE_GUEST_ACCESS"
)

type ExecuteClientActionVariantEnvelope struct {
	Action string `json:"action"`
}

// DecodeExecuteClientActionResponse decodes a variant response based on the action field.
func DecodeExecuteClientActionResponse(data []byte) (any, error) {
	var env ExecuteClientActionVariantEnvelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}

	switch env.Action {
	case "AUTHORIZE_GUEST_ACCESS":
		var out ExecuteClientActionResponseAuthorizeGuestAccess
		return &out, json.Unmarshal(data, &out)
	case "UNAUTHORIZE_GUEST_ACCESS":
		var out ExecuteClientActionResponseUnauthorizeGuestAccess
		return &out, json.Unmarshal(data, &out)
	default:
		return nil, fmt.Errorf("unknown action value: %s", env.Action)
	}
}
