// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Connected Client Details
// Method: GET /v1/sites/{siteId}/clients/{clientId}

package clients

import (
	"encoding/json"
	"fmt"
	"time"
)

// GetConnectedClientDetailsPathParams contains the path parameters for the GetConnectedClientDetails endpoint.
type GetConnectedClientDetailsPathParams struct {
	ClientId string `json:"clientId"`
	SiteId   string `json:"siteId"`
}

// GetConnectedClientDetailsResponseTeleport represents a nested object structure.
type GetConnectedClientDetailsResponseTeleport struct {
	Id          string     `json:"id"`
	Name        string     `json:"name"`
	ConnectedAt *time.Time `json:"connectedAt,omitempty"`
	IpAddress   string     `json:"ipAddress,omitempty"`
	// Represents the type of network access and/or any applicable authorization sta...
	Access *ClientAccess `json:"access"`
}

// GetConnectedClientDetailsResponseVpn represents a nested object structure.
type GetConnectedClientDetailsResponseVpn struct {
	Id          string     `json:"id"`
	Name        string     `json:"name"`
	ConnectedAt *time.Time `json:"connectedAt,omitempty"`
	IpAddress   string     `json:"ipAddress,omitempty"`
	Type        string     `json:"type"`
	// Represents the type of network access and/or any applicable authorization sta...
	Access *ClientAccess `json:"access"`
}

// GetConnectedClientDetailsResponseWired represents a nested object structure.
type GetConnectedClientDetailsResponseWired struct {
	Id          string     `json:"id"`
	Name        string     `json:"name"`
	ConnectedAt *time.Time `json:"connectedAt,omitempty"`
	IpAddress   string     `json:"ipAddress,omitempty"`
	Type        string     `json:"type"`
	// Represents the type of network access and/or any applicable authorization sta...
	Access         *ClientAccess `json:"access"`
	MacAddress     string        `json:"macAddress,omitempty"`
	UplinkDeviceId string        `json:"uplinkDeviceId,omitempty"`
}

// GetConnectedClientDetailsResponseWireless represents a nested object structure.
type GetConnectedClientDetailsResponseWireless struct {
	Id          string     `json:"id"`
	Name        string     `json:"name"`
	ConnectedAt *time.Time `json:"connectedAt,omitempty"`
	IpAddress   string     `json:"ipAddress,omitempty"`
	Type        string     `json:"type"`
	// Represents the type of network access and/or any applicable authorization sta...
	Access         *ClientAccess `json:"access"`
	MacAddress     string        `json:"macAddress,omitempty"`
	UplinkDeviceId string        `json:"uplinkDeviceId,omitempty"`
}

type GetConnectedClientDetailsVariantEnvelope struct {
	Type string `json:"type"`
}

// DecodeGetConnectedClientDetailsResponse decodes a variant response based on the type field.
func DecodeGetConnectedClientDetailsResponse(data []byte) (any, error) {
	var env GetConnectedClientDetailsVariantEnvelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}

	switch env.Type {
	case "TELEPORT":
		var out GetConnectedClientDetailsResponseTeleport
		return &out, json.Unmarshal(data, &out)
	case "VPN":
		var out GetConnectedClientDetailsResponseVpn
		return &out, json.Unmarshal(data, &out)
	case "WIRED":
		var out GetConnectedClientDetailsResponseWired
		return &out, json.Unmarshal(data, &out)
	case "WIRELESS":
		var out GetConnectedClientDetailsResponseWireless
		return &out, json.Unmarshal(data, &out)
	default:
		return nil, fmt.Errorf("unknown type value: %s", env.Type)
	}
}
