// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Connected Client Details
// Method: GET /v1/sites/{siteId}/clients/{clientId}

package clients

// GetConnectedClientDetailsPathParams contains the path parameters for the GetConnectedClientDetails endpoint.
type GetConnectedClientDetailsPathParams struct {
	ClientId string `json:"clientId"`
	SiteId   string `json:"siteId"`
}

// GetConnectedClientDetailsResponse is an alias for Client.
type GetConnectedClientDetailsResponse = Client
