// Code generated by clientgen. DO NOT EDIT.

package info

import (
	"context"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Info provides access to the Info API.
type Info struct {
	client *http.Client
}

// NewInfo creates a new Info instance.
func NewInfo(client *http.Client) *Info {
	return &Info{
		client: client,
	}
}

// GetApplicationInfo calls the GetApplicationInfo endpoint.
// GET /v1/info
func (c *Info) GetApplicationInfo(ctx context.Context) (*GetApplicationInfoResponse, error) {
	path := "/v1/info"
	var result GetApplicationInfoResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
