// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Site-To-Site VPN Tunnels
// Method: GET /v1/sites/{siteId}/vpn/site-to-site-tunnels

package site_to_site_tunnels

// ListSiteToSiteVPNTunnelsPathParams contains the path parameters for the ListSiteToSiteVPNTunnels endpoint.
type ListSiteToSiteVPNTunnelsPathParams struct {
	SiteId string `json:"siteId"`
}

// ListSiteToSiteVPNTunnelsResponse contains the response body from the ListSiteToSiteVPNTunnels endpoint.
type ListSiteToSiteVPNTunnelsResponse struct {
	PaginatedResponse
	Data []ListSiteToSiteVPNTunnelsData `json:"data"`
}

// ListSiteToSiteVPNTunnelsData represents a nested object structure.
type ListSiteToSiteVPNTunnelsData struct {
	Type     string                                `json:"type"`
	Id       string                                `json:"id"`
	Name     string                                `json:"name"`
	Metadata *ListSiteToSiteVPNTunnelsDataMetadata `json:"metadata"`
}

// ListSiteToSiteVPNTunnelsDataMetadata represents a nested object structure.
type ListSiteToSiteVPNTunnelsDataMetadata struct {
	Origin string `json:"origin"`
}
