// Code generated by clientgen. DO NOT EDIT.

package site_to_site_tunnels

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// SiteToSiteTunnels provides access to the SiteToSiteTunnels API.
type SiteToSiteTunnels struct {
	client *http.Client
}

// NewSiteToSiteTunnels creates a new SiteToSiteTunnels instance.
func NewSiteToSiteTunnels(client *http.Client) *SiteToSiteTunnels {
	return &SiteToSiteTunnels{
		client: client,
	}
}

// ListSiteToSiteVPNTunnels calls the ListSiteToSiteVPNTunnels endpoint.
// GET /v1/sites/{siteId}/vpn/site-to-site-tunnels
func (c *SiteToSiteTunnels) ListSiteToSiteVPNTunnels(ctx context.Context, siteId string) (*ListSiteToSiteVPNTunnelsResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/vpn/site-to-site-tunnels", siteId)
	var result ListSiteToSiteVPNTunnelsResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
