// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Devices Pending Adoption
// Method: GET /v1/pending-devices

package pending_devices

import (
	"encoding/json"
)

// ListDevicesPendingAdoptionResponse contains the response body from the ListDevicesPendingAdoption endpoint.
type ListDevicesPendingAdoptionResponse struct {
	PaginatedResponse
	Data []ListDevicesPendingAdoptionData `json:"data"`
}

// ListDevicesPendingAdoptionData represents a nested object structure.
type ListDevicesPendingAdoptionData struct {
	MacAddress        string            `json:"macAddress"`
	IpAddress         string            `json:"ipAddress"`
	Model             string            `json:"model"`
	State             string            `json:"state"`
	Supported         bool              `json:"supported"`
	FirmwareVersion   string            `json:"firmwareVersion,omitempty"`
	FirmwareUpdatable bool              `json:"firmwareUpdatable"`
	Features          []json.RawMessage `json:"features"`
}
