// Code generated by clientgen. DO NOT EDIT.

package pending_devices

import (
	"context"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// PendingDevices provides access to the PendingDevices API.
type PendingDevices struct {
	client *http.Client
}

// NewPendingDevices creates a new PendingDevices instance.
func NewPendingDevices(client *http.Client) *PendingDevices {
	return &PendingDevices{
		client: client,
	}
}

// ListDevicesPendingAdoption calls the ListDevicesPendingAdoption endpoint.
// GET /v1/pending-devices
func (c *PendingDevices) ListDevicesPendingAdoption(ctx context.Context) (*ListDevicesPendingAdoptionResponse, error) {
	path := "/v1/pending-devices"
	var result ListDevicesPendingAdoptionResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
