// Code generated by clientgen. DO NOT EDIT.

package acl_rules

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// AclRules provides access to the AclRules API.
type AclRules struct {
	client *http.Client
}

// NewAclRules creates a new AclRules instance.
func NewAclRules(client *http.Client) *AclRules {
	return &AclRules{
		client: client,
	}
}

// CreateACLRule calls the CreateACLRule endpoint.
// POST /v1/sites/{siteId}/acl-rules
func (c *AclRules) CreateACLRule(ctx context.Context, siteId string, req *CreateACLRuleRequest) (*CreateACLRuleResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/acl-rules", siteId)
	var result CreateACLRuleResponse
	if err := c.client.Post(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteACLRule calls the DeleteACLRule endpoint.
// DELETE /v1/sites/{siteId}/acl-rules/{aclRuleId}
func (c *AclRules) DeleteACLRule(ctx context.Context, aclRuleId string, siteId string) (*DeleteACLRuleResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/acl-rules/%s", aclRuleId, siteId)
	var result DeleteACLRuleResponse
	if err := c.client.Delete(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetACLRule calls the GetACLRule endpoint.
// GET /v1/sites/{siteId}/acl-rules/{aclRuleId}
func (c *AclRules) GetACLRule(ctx context.Context, aclRuleId string, siteId string) (*GetACLRuleResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/acl-rules/%s", aclRuleId, siteId)
	var result GetACLRuleResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListACLRules calls the ListACLRules endpoint.
// GET /v1/sites/{siteId}/acl-rules
func (c *AclRules) ListACLRules(ctx context.Context, siteId string) (*ListACLRulesResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/acl-rules", siteId)
	var result ListACLRulesResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateACLRule calls the UpdateACLRule endpoint.
// PUT /v1/sites/{siteId}/acl-rules/{aclRuleId}
func (c *AclRules) UpdateACLRule(ctx context.Context, aclRuleId string, siteId string, req *UpdateACLRuleRequest) (*UpdateACLRuleResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/acl-rules/%s", aclRuleId, siteId)
	var result UpdateACLRuleResponse
	if err := c.client.Put(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
