// Code generated by typegen. DO NOT EDIT.
// Endpoint: Create ACL Rule
// Method: POST /v1/sites/{siteId}/acl-rules

package acl_rules

import (
	"encoding/json"
	"fmt"
)

// CreateACLRulePathParams contains the path parameters for the CreateACLRule endpoint.
type CreateACLRulePathParams struct {
	SiteId string `json:"siteId"`
}

// CreateACLRuleRequestIpv4 represents a nested object structure.
type CreateACLRuleRequestIpv4 struct {
	Type    string `json:"type"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *CreateACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter *CreateACLRuleSourceFilter `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Protocols this ACL rule will be applied to. When null, the rule will be appli...
	ProtocolFilter []json.RawMessage `json:"protocolFilter,omitempty"`
}

// CreateACLRuleRequestMac represents a nested object structure.
type CreateACLRuleRequestMac struct {
	Type    string `json:"type"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *CreateACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter *CreateACLRuleSourceFilter `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Network ID to which this ACL rule applies
	NetworkIdFilter string `json:"networkIdFilter,omitempty"`
}

// CreateACLRuleResponseIpv4 represents a nested object structure.
type CreateACLRuleResponseIpv4 struct {
	Type    string `json:"type"`
	Id      string `json:"id"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *CreateACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter json.RawMessage `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Only user-defined rules can be deleted or modified
	Metadata *CreateACLRuleMetadata `json:"metadata"`
	// Protocols this ACL rule will be applied to. When null, the rule will be appli...
	ProtocolFilter []json.RawMessage `json:"protocolFilter,omitempty"`
}

// CreateACLRuleResponseMac represents a nested object structure.
type CreateACLRuleResponseMac struct {
	Type    string `json:"type"`
	Id      string `json:"id"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *CreateACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter json.RawMessage `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Only user-defined rules can be deleted or modified
	Metadata *CreateACLRuleMetadata `json:"metadata"`
	// Protocols this ACL rule will be applied to. When null, the rule will be appli...
	ProtocolFilter []json.RawMessage `json:"protocolFilter,omitempty"`
}

// CreateACLRuleMetadata represents a nested object structure.
type CreateACLRuleMetadata struct {
	Origin string `json:"origin"`
}

// CreateACLRuleEnforcingDeviceFilter represents a nested object structure.
type CreateACLRuleEnforcingDeviceFilter struct {
	Type string `json:"type"`
	// List of Switch capable device IDs to which the ACL rule will be provisioned.
	DeviceIds []json.RawMessage `json:"deviceIds,omitempty"`
}

// CreateACLRuleSourceFilter represents a nested object structure.
type CreateACLRuleSourceFilter struct {
	Type string `json:"type"`
	// Source/destination MAC addresses this ACL rule will apply to.
	MacAddresses []json.RawMessage `json:"macAddresses,omitempty"`
	// MAC address prefix length. When null, full MAC address(-es) will be used.
	PrefixLength int64 `json:"prefixLength,omitempty"`
}

// CreateACLRuleType represents the type enum values.
type CreateACLRuleType string

const (
	CreateACLRuleTypeIpv4 CreateACLRuleType = "IPV4"
	CreateACLRuleTypeMac  CreateACLRuleType = "MAC"
)

type CreateACLRuleVariantEnvelope struct {
	Type string `json:"type"`
}

// DecodeCreateACLRuleResponse decodes a variant response based on the type field.
func DecodeCreateACLRuleResponse(data []byte) (any, error) {
	var env CreateACLRuleVariantEnvelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}

	switch env.Type {
	case "IPV4":
		var out CreateACLRuleResponseIpv4
		return &out, json.Unmarshal(data, &out)
	case "MAC":
		var out CreateACLRuleResponseMac
		return &out, json.Unmarshal(data, &out)
	default:
		return nil, fmt.Errorf("unknown type value: %s", env.Type)
	}
}
