// Code generated by typegen. DO NOT EDIT.
// Endpoint: Create ACL Rule
// Method: POST /v1/sites/{siteId}/acl-rules

package acl_rules

import (
	"encoding/json"
)

// CreateACLRulePathParams contains the path parameters for the CreateACLRule endpoint.
type CreateACLRulePathParams struct {
	SiteId string `json:"siteId"`
}

// CreateACLRuleRequest contains the request body for the CreateACLRule endpoint.
type CreateACLRuleRequest struct {
	Type    string `json:"type"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *CreateACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter *CreateACLRuleSourceFilter `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Protocols this ACL rule will be applied to. When null, the rule will be appli...
	ProtocolFilter []json.RawMessage `json:"protocolFilter,omitempty"`
}

// CreateACLRuleResponse contains the response body from the CreateACLRule endpoint.
type CreateACLRuleResponse struct {
	Type    string `json:"type"`
	Id      string `json:"id"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *CreateACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter json.RawMessage `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Only user-defined rules can be deleted or modified
	Metadata *CreateACLRuleMetadata `json:"metadata"`
	// Protocols this ACL rule will be applied to. When null, the rule will be appli...
	ProtocolFilter []json.RawMessage `json:"protocolFilter,omitempty"`
}

// CreateACLRuleEnforcingDeviceFilter represents a nested object structure.
type CreateACLRuleEnforcingDeviceFilter struct {
	Type string `json:"type"`
	// List of Switch capable device IDs to which the ACL rule will be provisioned.
	DeviceIds []json.RawMessage `json:"deviceIds,omitempty"`
}

// CreateACLRuleSourceFilter represents a nested object structure.
type CreateACLRuleSourceFilter struct {
	Type string `json:"type"`
	// IP addresses or subnets
	IpAddressesOrSubnets []json.RawMessage `json:"ipAddressesOrSubnets,omitempty"`
	// Ports this ACL rule will be applied to. If null, all the rule will be applied...
	PortFilter []json.RawMessage `json:"portFilter,omitempty"`
}

// CreateACLRuleMetadata represents a nested object structure.
type CreateACLRuleMetadata struct {
	Origin string `json:"origin"`
}

// CreateACLRuleType represents the type enum values.
type CreateACLRuleType string

const (
	CreateACLRuleTypeIpv4 CreateACLRuleType = "IPV4"
	CreateACLRuleTypeMac  CreateACLRuleType = "MAC"
)
