// Code generated by typegen. DO NOT EDIT.
// Endpoint: Delete ACL Rule
// Method: DELETE /v1/sites/{siteId}/acl-rules/{aclRuleId}

package acl_rules

// DeleteACLRulePathParams contains the path parameters for the DeleteACLRule endpoint.
type DeleteACLRulePathParams struct {
	AclRuleId string `json:"aclRuleId"`
	SiteId    string `json:"siteId"`
}

// DeleteACLRuleResponse represents the API response for Delete ACL Rule.
type DeleteACLRuleResponse struct{}
