// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get ACL Rule
// Method: GET /v1/sites/{siteId}/acl-rules/{aclRuleId}

package acl_rules

import (
	"encoding/json"
)

// GetACLRulePathParams contains the path parameters for the GetACLRule endpoint.
type GetACLRulePathParams struct {
	AclRuleId string `json:"aclRuleId"`
	SiteId    string `json:"siteId"`
}

// GetACLRuleResponse contains the response body from the GetACLRule endpoint.
type GetACLRuleResponse struct {
	Type    string `json:"type"`
	Id      string `json:"id"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *GetACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter json.RawMessage `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Only user-defined rules can be deleted or modified
	Metadata *GetACLRuleMetadata `json:"metadata"`
	// Protocols this ACL rule will be applied to. When null, the rule will be appli...
	ProtocolFilter []json.RawMessage `json:"protocolFilter,omitempty"`
}

// GetACLRuleEnforcingDeviceFilter represents a nested object structure.
type GetACLRuleEnforcingDeviceFilter struct {
	Type string `json:"type"`
	// List of Switch capable device IDs to which the ACL rule will be provisioned.
	DeviceIds []json.RawMessage `json:"deviceIds,omitempty"`
}

// GetACLRuleMetadata represents a nested object structure.
type GetACLRuleMetadata struct {
	Origin string `json:"origin"`
}
