// Code generated by typegen. DO NOT EDIT.
// Endpoint: List ACL Rules
// Method: GET /v1/sites/{siteId}/acl-rules

package acl_rules

import (
	"encoding/json"
)

// ListACLRulesPathParams contains the path parameters for the ListACLRules endpoint.
type ListACLRulesPathParams struct {
	SiteId string `json:"siteId"`
}

// ListACLRulesResponse contains the response body from the ListACLRules endpoint.
type ListACLRulesResponse struct {
	PaginatedResponse
	Data []ListACLRulesData `json:"data"`
}

// ListACLRulesData represents a nested object structure.
type ListACLRulesData struct {
	Type    string `json:"type"`
	Id      string `json:"id"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *ListACLRulesDataEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter json.RawMessage `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Only user-defined rules can be deleted or modified
	Metadata *ListACLRulesDataMetadata `json:"metadata"`
	// Protocols this ACL rule will be applied to. When null, the rule will be appli...
	ProtocolFilter []json.RawMessage `json:"protocolFilter,omitempty"`
}

// ListACLRulesDataMetadata represents a nested object structure.
type ListACLRulesDataMetadata struct {
	Origin string `json:"origin"`
}

// ListACLRulesDataEnforcingDeviceFilter represents a nested object structure.
type ListACLRulesDataEnforcingDeviceFilter struct {
	Type string `json:"type"`
	// List of Switch capable device IDs to which the ACL rule will be provisioned.
	DeviceIds []json.RawMessage `json:"deviceIds,omitempty"`
}
