// Code generated by typegen. DO NOT EDIT.
// Endpoint: Update ACL Rule
// Method: PUT /v1/sites/{siteId}/acl-rules/{aclRuleId}

package acl_rules

import (
	"encoding/json"
)

// UpdateACLRulePathParams contains the path parameters for the UpdateACLRule endpoint.
type UpdateACLRulePathParams struct {
	AclRuleId string `json:"aclRuleId"`
	SiteId    string `json:"siteId"`
}

// UpdateACLRuleRequest contains the request body for the UpdateACLRule endpoint.
type UpdateACLRuleRequest struct {
	Type    string `json:"type"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *UpdateACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter *UpdateACLRuleSourceFilter `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Protocols this ACL rule will be applied to. When null, the rule will be appli...
	ProtocolFilter []json.RawMessage `json:"protocolFilter,omitempty"`
}

// UpdateACLRuleResponse contains the response body from the UpdateACLRule endpoint.
type UpdateACLRuleResponse struct {
	Type    string `json:"type"`
	Id      string `json:"id"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *UpdateACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter json.RawMessage `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Only user-defined rules can be deleted or modified
	Metadata *UpdateACLRuleMetadata `json:"metadata"`
	// Protocols this ACL rule will be applied to. When null, the rule will be appli...
	ProtocolFilter []json.RawMessage `json:"protocolFilter,omitempty"`
}

// UpdateACLRuleEnforcingDeviceFilter represents a nested object structure.
type UpdateACLRuleEnforcingDeviceFilter struct {
	Type string `json:"type"`
	// List of Switch capable device IDs to which the ACL rule will be provisioned.
	DeviceIds []json.RawMessage `json:"deviceIds,omitempty"`
}

// UpdateACLRuleSourceFilter represents a nested object structure.
type UpdateACLRuleSourceFilter struct {
	Type string `json:"type"`
	// IP addresses or subnets
	IpAddressesOrSubnets []json.RawMessage `json:"ipAddressesOrSubnets,omitempty"`
	// Ports this ACL rule will be applied to. If null, all the rule will be applied...
	PortFilter []json.RawMessage `json:"portFilter,omitempty"`
}

// UpdateACLRuleMetadata represents a nested object structure.
type UpdateACLRuleMetadata struct {
	Origin string `json:"origin"`
}

// UpdateACLRuleType represents the type enum values.
type UpdateACLRuleType string

const (
	UpdateACLRuleTypeIpv4 UpdateACLRuleType = "IPV4"
	UpdateACLRuleTypeMac  UpdateACLRuleType = "MAC"
)
