// Code generated by typegen. DO NOT EDIT.
// Endpoint: Update ACL Rule
// Method: PUT /v1/sites/{siteId}/acl-rules/{aclRuleId}

package acl_rules

import (
	"encoding/json"
	"fmt"
)

// UpdateACLRulePathParams contains the path parameters for the UpdateACLRule endpoint.
type UpdateACLRulePathParams struct {
	AclRuleId string `json:"aclRuleId"`
	SiteId    string `json:"siteId"`
}

// UpdateACLRuleRequestIpv4 represents a nested object structure.
type UpdateACLRuleRequestIpv4 struct {
	Type    string `json:"type"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *UpdateACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter *UpdateACLRuleSourceFilter `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Protocols this ACL rule will be applied to. When null, the rule will be appli...
	ProtocolFilter []json.RawMessage `json:"protocolFilter,omitempty"`
}

// UpdateACLRuleRequestMac represents a nested object structure.
type UpdateACLRuleRequestMac struct {
	Type    string `json:"type"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *UpdateACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter *UpdateACLRuleSourceFilter `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Network ID to which this ACL rule applies
	NetworkIdFilter string `json:"networkIdFilter,omitempty"`
}

// UpdateACLRuleResponseIpv4 represents a nested object structure.
type UpdateACLRuleResponseIpv4 struct {
	Type    string `json:"type"`
	Id      string `json:"id"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *UpdateACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter json.RawMessage `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Only user-defined rules can be deleted or modified
	Metadata *UpdateACLRuleMetadata `json:"metadata"`
	// Protocols this ACL rule will be applied to. When null, the rule will be appli...
	ProtocolFilter []json.RawMessage `json:"protocolFilter,omitempty"`
}

// UpdateACLRuleResponseMac represents a nested object structure.
type UpdateACLRuleResponseMac struct {
	Type    string `json:"type"`
	Id      string `json:"id"`
	Enabled bool   `json:"enabled"`
	// ACL rule name
	Name string `json:"name"`
	// ACL rule description
	Description string `json:"description,omitempty"`
	// ACL rule action
	Action string `json:"action"`
	// IDs of the Switch-capable devices used to enforce the ACL rule. When null, th...
	EnforcingDeviceFilter *UpdateACLRuleEnforcingDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	// ACL rule index. Lower index has higher priority
	Index int64 `json:"index"`
	// Traffic source filter
	SourceFilter json.RawMessage `json:"sourceFilter,omitempty"`
	// Traffic destination filter
	DestinationFilter json.RawMessage `json:"destinationFilter,omitempty"`
	// Only user-defined rules can be deleted or modified
	Metadata *UpdateACLRuleMetadata `json:"metadata"`
	// Protocols this ACL rule will be applied to. When null, the rule will be appli...
	ProtocolFilter []json.RawMessage `json:"protocolFilter,omitempty"`
}

// UpdateACLRuleEnforcingDeviceFilter represents a nested object structure.
type UpdateACLRuleEnforcingDeviceFilter struct {
	Type string `json:"type"`
	// List of Switch capable device IDs to which the ACL rule will be provisioned.
	DeviceIds []json.RawMessage `json:"deviceIds,omitempty"`
}

// UpdateACLRuleSourceFilter represents a nested object structure.
type UpdateACLRuleSourceFilter struct {
	Type string `json:"type"`
	// Source/destination MAC addresses this ACL rule will apply to.
	MacAddresses []json.RawMessage `json:"macAddresses,omitempty"`
	// MAC address prefix length. When null, full MAC address(-es) will be used.
	PrefixLength int64 `json:"prefixLength,omitempty"`
}

// UpdateACLRuleMetadata represents a nested object structure.
type UpdateACLRuleMetadata struct {
	Origin string `json:"origin"`
}

// UpdateACLRuleType represents the type enum values.
type UpdateACLRuleType string

const (
	UpdateACLRuleTypeIpv4 UpdateACLRuleType = "IPV4"
	UpdateACLRuleTypeMac  UpdateACLRuleType = "MAC"
)

type UpdateACLRuleVariantEnvelope struct {
	Type string `json:"type"`
}

// DecodeUpdateACLRuleResponse decodes a variant response based on the type field.
func DecodeUpdateACLRuleResponse(data []byte) (any, error) {
	var env UpdateACLRuleVariantEnvelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}

	switch env.Type {
	case "IPV4":
		var out UpdateACLRuleResponseIpv4
		return &out, json.Unmarshal(data, &out)
	case "MAC":
		var out UpdateACLRuleResponseMac
		return &out, json.Unmarshal(data, &out)
	default:
		return nil, fmt.Errorf("unknown type value: %s", env.Type)
	}
}
