// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Radius Profiles
// Method: GET /v1/sites/{siteId}/radius/profiles

package profiles

// ListRadiusProfilesPathParams contains the path parameters for the ListRadiusProfiles endpoint.
type ListRadiusProfilesPathParams struct {
	SiteId string `json:"siteId"`
}

// ListRadiusProfilesResponse contains the response body from the ListRadiusProfiles endpoint.
type ListRadiusProfilesResponse struct {
	PaginatedResponse
	Data []ListRadiusProfilesData `json:"data"`
}

// ListRadiusProfilesData represents a nested object structure.
type ListRadiusProfilesData struct {
	Id       string                          `json:"id"`
	Name     string                          `json:"name"`
	Metadata *ListRadiusProfilesDataMetadata `json:"metadata"`
}

// ListRadiusProfilesDataMetadata represents a nested object structure.
type ListRadiusProfilesDataMetadata struct {
	Origin string `json:"origin"`
}
