// Code generated by clientgen. DO NOT EDIT.

package profiles

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Profiles provides access to the Profiles API.
type Profiles struct {
	client *http.Client
}

// NewProfiles creates a new Profiles instance.
func NewProfiles(client *http.Client) *Profiles {
	return &Profiles{
		client: client,
	}
}

// ListRadiusProfiles calls the ListRadiusProfiles endpoint.
// GET /v1/sites/{siteId}/radius/profiles
func (c *Profiles) ListRadiusProfiles(ctx context.Context, siteId string) (*ListRadiusProfilesResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/radius/profiles", siteId)
	var result ListRadiusProfilesResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
