package typegen

import (
	"strings"
)

// CommonType represents a shared type that can be reused across endpoints.
type CommonType struct {
	Name      string   // Type name (e.g., "Voucher")
	Fields    []string // Required field names for matching
	IsArray   bool     // Whether this is typically used as an array
	MinFields int      // Minimum number of fields to match
	MaxFields int      // Maximum number of fields (0 = no limit)
}

// commonTypes defines the shared types and their identifying fields.
var commonTypes = []CommonType{
	{
		Name:      "Voucher",
		Fields:    []string{"id", "createdAt", "code", "expired", "timeLimitMinutes"},
		MinFields: 4,
	},
	{
		Name:      "Client",
		Fields:    []string{"id", "name", "type", "access", "macAddress"},
		MinFields: 4,
	},
	{
		Name:      "ClientAccess",
		Fields:    []string{"type"},
		MinFields: 1,
		MaxFields: 1,
	},
	{
		Name:      "Site",
		Fields:    []string{"id", "name", "internalReference"},
		MinFields: 3,
	},
	{
		Name:      "Authorization",
		Fields:    []string{"authorizedAt", "authorizationMethod", "expiresAt"},
		MinFields: 3,
	},
	{
		Name:      "AuthorizationUsage",
		Fields:    []string{"durationSec", "rxBytes", "txBytes", "bytes"},
		MinFields: 4,
	},
	{
		Name:      "PaginatedResponse",
		Fields:    []string{"offset", "limit", "count", "totalCount"},
		MinFields: 4,
	},
}

// matchCommonType checks if properties match a common type and returns its name.
func matchCommonType(props []Property) string {
	propNames := make(map[string]bool)
	for _, p := range props {
		propNames[strings.ToLower(p.Name)] = true
	}

	for _, ct := range commonTypes {
		if ct.MaxFields > 0 && len(props) > ct.MaxFields {
			continue
		}

		matchCount := 0
		for _, field := range ct.Fields {
			if propNames[strings.ToLower(field)] {
				matchCount++
			}
		}
		if matchCount >= ct.MinFields {
			return ct.Name
		}
	}
	return ""
}

// isPaginatedResponse checks if the properties indicate a paginated response.
func isPaginatedResponse(props []Property) bool {
	required := []string{"offset", "limit", "count", "totalcount"}
	found := 0
	for _, p := range props {
		for _, r := range required {
			if strings.ToLower(p.Name) == r {
				found++
				break
			}
		}
	}
	return found >= 4
}

// isPaginationField checks if a field name is a pagination field.
func isPaginationField(name string) bool {
	paginationFields := []string{"offset", "limit", "count", "totalcount"}
	lowerName := strings.ToLower(name)
	for _, f := range paginationFields {
		if lowerName == f {
			return true
		}
	}
	return false
}

// generateCommonTypesCode generates common shared types code.
func generateCommonTypesCode(pkgName string) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by typegen. DO NOT EDIT.\n")
	sb.WriteString("// Common types shared across multiple endpoints.\n\n")
	sb.WriteString("package ")
	sb.WriteString(pkgName)
	sb.WriteString("\n\n")
	sb.WriteString("import (\n\t\"encoding/json\"\n\t\"time\"\n)\n\n")

	sb.WriteString(`// PaginatedResponse contains pagination metadata for list endpoints.
type PaginatedResponse struct {
	Offset     int64 ` + "`json:\"offset\"`" + `
	Limit      int64 ` + "`json:\"limit\"`" + `
	Count      int64 ` + "`json:\"count\"`" + `
	TotalCount int64 ` + "`json:\"totalCount\"`" + `
}

`)

	sb.WriteString(`// Voucher represents a hotspot voucher.
type Voucher struct {
	Id                   string     ` + "`json:\"id\"`" + `
	CreatedAt            time.Time  ` + "`json:\"createdAt\"`" + `
	Name                 string     ` + "`json:\"name\"`" + `
	Code                 string     ` + "`json:\"code\"`" + `
	AuthorizedGuestLimit int64      ` + "`json:\"authorizedGuestLimit,omitempty\"`" + `
	AuthorizedGuestCount int64      ` + "`json:\"authorizedGuestCount\"`" + `
	ActivatedAt          *time.Time ` + "`json:\"activatedAt,omitempty\"`" + `
	ExpiresAt            *time.Time ` + "`json:\"expiresAt,omitempty\"`" + `
	Expired              bool       ` + "`json:\"expired\"`" + `
	TimeLimitMinutes     int64      ` + "`json:\"timeLimitMinutes\"`" + `
	DataUsageLimitMBytes int64      ` + "`json:\"dataUsageLimitMBytes,omitempty\"`" + `
	RxRateLimitKbps      int64      ` + "`json:\"rxRateLimitKbps,omitempty\"`" + `
	TxRateLimitKbps      int64      ` + "`json:\"txRateLimitKbps,omitempty\"`" + `
}

`)

	sb.WriteString(`// Client represents a connected network client.
type Client struct {
	Id             string        ` + "`json:\"id\"`" + `
	Name           string        ` + "`json:\"name\"`" + `
	ConnectedAt    *time.Time    ` + "`json:\"connectedAt,omitempty\"`" + `
	IpAddress      string        ` + "`json:\"ipAddress,omitempty\"`" + `
	Access         *ClientAccess ` + "`json:\"access\"`" + `
	Type           string        ` + "`json:\"type\"`" + `
	MacAddress     string        ` + "`json:\"macAddress,omitempty\"`" + `
	UplinkDeviceId string        ` + "`json:\"uplinkDeviceId,omitempty\"`" + `
}

// ClientAccess represents the network access type and authorization status.
type ClientAccess struct {
	Type string ` + "`json:\"type\"`" + `
}

`)

	sb.WriteString(`// Authorization represents a guest authorization.
type Authorization struct {
	AuthorizedAt         time.Time           ` + "`json:\"authorizedAt\"`" + `
	AuthorizationMethod  string              ` + "`json:\"authorizationMethod\"`" + `
	ExpiresAt            time.Time           ` + "`json:\"expiresAt\"`" + `
	DataUsageLimitMBytes int64               ` + "`json:\"dataUsageLimitMBytes,omitempty\"`" + `
	RxRateLimitKbps      int64               ` + "`json:\"rxRateLimitKbps,omitempty\"`" + `
	TxRateLimitKbps      int64               ` + "`json:\"txRateLimitKbps,omitempty\"`" + `
	Usage                *AuthorizationUsage ` + "`json:\"usage,omitempty\"`" + `
}

// AuthorizationUsage represents usage statistics for an authorization.
type AuthorizationUsage struct {
	DurationSec int64 ` + "`json:\"durationSec\"`" + `
	RxBytes     int64 ` + "`json:\"rxBytes\"`" + `
	TxBytes     int64 ` + "`json:\"txBytes\"`" + `
	Bytes       int64 ` + "`json:\"bytes\"`" + `
}

`)

	sb.WriteString(`// Site represents a UniFi site.
type Site struct {
	Id                string ` + "`json:\"id\"`" + `
	InternalReference string ` + "`json:\"internalReference\"`" + `
	Name              string ` + "`json:\"name\"`" + `
}

`)

	sb.WriteString(`// Device represents an adopted UniFi device.
type Device struct {
	Id                string            ` + "`json:\"id\"`" + `
	Name              string            ` + "`json:\"name\"`" + `
	Model             string            ` + "`json:\"model\"`" + `
	MacAddress        string            ` + "`json:\"macAddress\"`" + `
	IpAddress         string            ` + "`json:\"ipAddress\"`" + `
	State             string            ` + "`json:\"state\"`" + `
	Supported         bool              ` + "`json:\"supported,omitempty\"`" + `
	FirmwareVersion   string            ` + "`json:\"firmwareVersion,omitempty\"`" + `
	FirmwareUpdatable bool              ` + "`json:\"firmwareUpdatable,omitempty\"`" + `
	AdoptedAt         *time.Time        ` + "`json:\"adoptedAt,omitempty\"`" + `
	ProvisionedAt     *time.Time        ` + "`json:\"provisionedAt,omitempty\"`" + `
	ConfigurationId   string            ` + "`json:\"configurationId,omitempty\"`" + `
	Uplink            *DeviceUplink     ` + "`json:\"uplink,omitempty\"`" + `
	Features          *DeviceFeatures   ` + "`json:\"features,omitempty\"`" + `
	Interfaces        *DeviceInterfaces ` + "`json:\"interfaces,omitempty\"`" + `
}

// DeviceUplink represents the device's uplink connection.
type DeviceUplink struct {
	DeviceId  string ` + "`json:\"deviceId\"`" + `
	TxRateBps int64  ` + "`json:\"txRateBps,omitempty\"`" + `
	RxRateBps int64  ` + "`json:\"rxRateBps,omitempty\"`" + `
}

// DeviceFeatures represents device feature capabilities.
type DeviceFeatures struct {
	Switching   json.RawMessage ` + "`json:\"switching,omitempty\"`" + `
	AccessPoint json.RawMessage ` + "`json:\"accessPoint,omitempty\"`" + `
}

// DeviceInterfaces represents device network interfaces.
type DeviceInterfaces struct {
	Ports  []DevicePort  ` + "`json:\"ports,omitempty\"`" + `
	Radios []DeviceRadio ` + "`json:\"radios,omitempty\"`" + `
}

// DevicePort represents a network port on a device.
type DevicePort struct {
	Idx          int64      ` + "`json:\"idx\"`" + `
	State        string     ` + "`json:\"state\"`" + `
	Connector    string     ` + "`json:\"connector\"`" + `
	MaxSpeedMbps int64      ` + "`json:\"maxSpeedMbps\"`" + `
	SpeedMbps    int64      ` + "`json:\"speedMbps,omitempty\"`" + `
	Poe          *DevicePoe ` + "`json:\"poe,omitempty\"`" + `
}

// DevicePoe represents PoE configuration for a port.
type DevicePoe struct {
	Standard string ` + "`json:\"standard\"`" + `
	Type     int64  ` + "`json:\"type\"`" + `
	Enabled  bool   ` + "`json:\"enabled\"`" + `
	State    string ` + "`json:\"state\"`" + `
}

// DeviceRadio represents a wireless radio interface.
type DeviceRadio struct {
	WlanStandard    string  ` + "`json:\"wlanStandard\"`" + `
	FrequencyGHz    float64 ` + "`json:\"frequencyGHz\"`" + `
	ChannelWidthMHz int64   ` + "`json:\"channelWidthMHz\"`" + `
	Channel         int64   ` + "`json:\"channel,omitempty\"`" + `
	TxRetriesPct    float64 ` + "`json:\"txRetriesPct,omitempty\"`" + `
}

`)

	sb.WriteString(`// DeviceStatistics represents device runtime statistics.
type DeviceStatistics struct {
	UptimeSec            int64      ` + "`json:\"uptimeSec,omitempty\"`" + `
	LastHeartbeatAt      *time.Time ` + "`json:\"lastHeartbeatAt,omitempty\"`" + `
	NextHeartbeatAt      *time.Time ` + "`json:\"nextHeartbeatAt,omitempty\"`" + `
	LoadAverage1Min      float64    ` + "`json:\"loadAverage1Min,omitempty\"`" + `
	LoadAverage5Min      float64    ` + "`json:\"loadAverage5Min,omitempty\"`" + `
	LoadAverage15Min     float64    ` + "`json:\"loadAverage15Min,omitempty\"`" + `
	CpuUtilizationPct    float64    ` + "`json:\"cpuUtilizationPct,omitempty\"`" + `
	MemoryUtilizationPct float64    ` + "`json:\"memoryUtilizationPct,omitempty\"`" + `
}

`)

	return sb.String()
}
