// Code generated by typegen. DO NOT EDIT.
// Endpoint: List VPN Servers
// Method: GET /v1/sites/{siteId}/vpn/servers

package servers

// ListVPNServersPathParams contains the path parameters for the ListVPNServers endpoint.
type ListVPNServersPathParams struct {
	SiteId string `json:"siteId"`
}

// ListVPNServersResponse contains the response body from the ListVPNServers endpoint.
type ListVPNServersResponse struct {
	PaginatedResponse
	Data []ListVPNServersData `json:"data"`
}

// ListVPNServersData represents a nested object structure.
type ListVPNServersData struct {
	Type     string                      `json:"type"`
	Id       string                      `json:"id"`
	Name     string                      `json:"name"`
	Enabled  bool                        `json:"enabled"`
	Metadata *ListVPNServersDataMetadata `json:"metadata"`
}

// ListVPNServersDataMetadata represents a nested object structure.
type ListVPNServersDataMetadata struct {
	Origin string `json:"origin"`
}
