// Code generated by clientgen. DO NOT EDIT.

package servers

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Servers provides access to the Servers API.
type Servers struct {
	client *http.Client
}

// NewServers creates a new Servers instance.
func NewServers(client *http.Client) *Servers {
	return &Servers{
		client: client,
	}
}

// ListVPNServers calls the ListVPNServers endpoint.
// GET /v1/sites/{siteId}/vpn/servers
func (c *Servers) ListVPNServers(ctx context.Context, siteId string) (*ListVPNServersResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/vpn/servers", siteId)
	var result ListVPNServersResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
