// Code generated by clientgen. DO NOT EDIT.

package applications

import (
	"context"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Applications provides access to the Applications API.
type Applications struct {
	client *http.Client
}

// NewApplications creates a new Applications instance.
func NewApplications(client *http.Client) *Applications {
	return &Applications{
		client: client,
	}
}

// ListDPIApplications calls the ListDPIApplications endpoint.
// GET /v1/dpi/applications
func (c *Applications) ListDPIApplications(ctx context.Context) (*ListDPIApplicationsResponse, error) {
	path := "/v1/dpi/applications"
	var result ListDPIApplicationsResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
