// Code generated by typegen. DO NOT EDIT.
// Endpoint: List DPI Applications
// Method: GET /v1/dpi/applications

package applications

// ListDPIApplicationsResponse contains the response body from the ListDPIApplications endpoint.
type ListDPIApplicationsResponse struct {
	PaginatedResponse
	Data []ListDPIApplicationsData `json:"data"`
}

// ListDPIApplicationsData represents a nested object structure.
type ListDPIApplicationsData struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}
