// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Network References
// Method: GET /v1/sites/{siteId}/networks/{networkId}/references

package references

// GetNetworkReferencesPathParams contains the path parameters for the GetNetworkReferences endpoint.
type GetNetworkReferencesPathParams struct {
	NetworkId string `json:"networkId"`
	SiteId    string `json:"siteId"`
}

// GetNetworkReferencesResponse contains the response body from the GetNetworkReferences endpoint.
type GetNetworkReferencesResponse struct {
	// List of network reference resources
	ReferenceResources []GetNetworkReferencesReferenceResources `json:"referenceResources"`
}

// GetNetworkReferencesReferenceResources represents a nested object structure.
type GetNetworkReferencesReferenceResources struct {
	ResourceType string `json:"resourceType"`
	// Number of references of this type
	ReferenceCount int64 `json:"referenceCount"`
	// List of references, present only if resourceType has API model defined
	References []GetNetworkReferencesReferenceResourcesReferences `json:"references,omitempty"`
}

// GetNetworkReferencesReferenceResourcesReferences represents a nested object structure.
type GetNetworkReferencesReferenceResourcesReferences struct {
	ReferenceId string `json:"referenceId"`
}
