// Code generated by clientgen. DO NOT EDIT.

package references

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// References provides access to the References API.
type References struct {
	client *http.Client
}

// NewReferences creates a new References instance.
func NewReferences(client *http.Client) *References {
	return &References{
		client: client,
	}
}

// GetNetworkReferences calls the GetNetworkReferences endpoint.
// GET /v1/sites/{siteId}/networks/{networkId}/references
func (c *References) GetNetworkReferences(ctx context.Context, networkId string, siteId string) (*GetNetworkReferencesResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/networks/%s/references", networkId, siteId)
	var result GetNetworkReferencesResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
