// Code generated by typegen. DO NOT EDIT.
// Endpoint: Create Network
// Method: POST /v1/sites/{siteId}/networks

package networks

import (
	"encoding/json"
	"fmt"
)

// CreateNetworkPathParams contains the path parameters for the CreateNetwork endpoint.
type CreateNetworkPathParams struct {
	SiteId string `json:"siteId"`
}

// CreateNetworkRequestGateway represents a nested object structure.
type CreateNetworkRequestGateway struct {
	Management string `json:"management"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *CreateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
	// Whether this network is isolated from all other networks.
	IsolationEnabled bool `json:"isolationEnabled,omitempty"`
	// Whether this network is allowed to use cellular data when WAN connection(s) a...
	CellularBackupEnabled bool `json:"cellularBackupEnabled,omitempty"`
	// Firewall zone ID associated with this Network.
	ZoneId string `json:"zoneId,omitempty"`
	// Whether the internet access is allowed for the device on this network.
	InternetAccessEnabled bool `json:"internetAccessEnabled,omitempty"`
	// Whether this network should participate in mDNS traffic forwarding.
	MdnsForwardingEnabled bool `json:"mdnsForwardingEnabled,omitempty"`
	// Details about IPv4 configuration for this Network.
	Ipv4Configuration *CreateNetworkIpv4Configuration `json:"ipv4Configuration,omitempty"`
	// Details about IPv6 configuration for this Network. If this field is omitted o...
	Ipv6Configuration *CreateNetworkIpv6Configuration `json:"ipv6Configuration,omitempty"`
}

// CreateNetworkRequestSwitch represents a nested object structure.
type CreateNetworkRequestSwitch struct {
	Management string `json:"management"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *CreateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
	// Whether this network is isolated from all other networks.
	IsolationEnabled bool `json:"isolationEnabled,omitempty"`
	// Whether this network is allowed to use cellular data when WAN connection(s) a...
	CellularBackupEnabled bool `json:"cellularBackupEnabled,omitempty"`
	// ID of the L3 switching capable device that manages this network.
	DeviceId string `json:"deviceId,omitempty"`
	// Details about IPv4 configuration for this Network.
	Ipv4Configuration *CreateNetworkIpv4Configuration `json:"ipv4Configuration,omitempty"`
}

// CreateNetworkRequestUnmanaged represents a nested object structure.
type CreateNetworkRequestUnmanaged struct {
	Management string `json:"management"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *CreateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// CreateNetworkResponseGateway represents a nested object structure.
type CreateNetworkResponseGateway struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *CreateNetworkMetadata `json:"metadata"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *CreateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// CreateNetworkResponseSwitch represents a nested object structure.
type CreateNetworkResponseSwitch struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *CreateNetworkMetadata `json:"metadata"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *CreateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// CreateNetworkResponseUnmanaged represents a nested object structure.
type CreateNetworkResponseUnmanaged struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *CreateNetworkMetadata `json:"metadata"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *CreateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// CreateNetworkIpv4ConfigurationDhcpConfigurationIpAddressRange represents a nested object structure.
type CreateNetworkIpv4ConfigurationDhcpConfigurationIpAddressRange struct {
	Start string `json:"start"`
	Stop  string `json:"stop"`
}

// CreateNetworkDhcpGuarding represents a nested object structure.
type CreateNetworkDhcpGuarding struct {
	// List of trusted DHCP server IP addresses.
	TrustedDhcpServerIpAddresses []json.RawMessage `json:"trustedDhcpServerIpAddresses"`
}

// CreateNetworkMetadata represents a nested object structure.
type CreateNetworkMetadata struct {
	Origin string `json:"origin"`
}

// CreateNetworkIpv4Configuration represents a nested object structure.
type CreateNetworkIpv4Configuration struct {
	// Whether the Network can automatically scale its subnet size based on the numb...
	AutoScaleEnabled bool   `json:"autoScaleEnabled"`
	HostIpAddress    string `json:"hostIpAddress"`
	PrefixLength     int64  `json:"prefixLength"`
	// Additional host IP subnets assigned to this VLAN.
	AdditionalHostIpSubnets []json.RawMessage `json:"additionalHostIpSubnets,omitempty"`
	// IPv4 DHCP configuration for this network. If this field is omitted or null, D...
	DhcpConfiguration *CreateNetworkIpv4ConfigurationDhcpConfiguration `json:"dhcpConfiguration,omitempty"`
}

// CreateNetworkIpv4ConfigurationDhcpConfigurationPxeConfiguration represents a nested object structure.
type CreateNetworkIpv4ConfigurationDhcpConfigurationPxeConfiguration struct {
	ServerIpAddress string `json:"serverIpAddress"`
	Filename        string `json:"filename"`
}

// CreateNetworkIpv4ConfigurationNatOutboundIpAddressConfiguration represents a nested object structure.
type CreateNetworkIpv4ConfigurationNatOutboundIpAddressConfiguration struct {
	Type           string `json:"type"`
	WanInterfaceId string `json:"wanInterfaceId"`
	// IP address selection mode which determines how the IP address will be selecte...
	IpAddressSelectionMode string `json:"ipAddressSelectionMode,omitempty"`
}

// CreateNetworkIpv6Configuration represents a nested object structure.
type CreateNetworkIpv6Configuration struct {
	InterfaceType string `json:"interfaceType"`
	// Client Address Assignment
	ClientAddressAssignment *CreateNetworkIpv6ConfigurationClientAddressAssignment `json:"clientAddressAssignment"`
	// Router advertisement. Without it, hosts will not autoconfigure addresses and ...
	RouterAdvertisement *CreateNetworkIpv6ConfigurationRouterAdvertisement `json:"routerAdvertisement,omitempty"`
	// The IPv6 DNS server addresses assigned to this Network. If none are specified...
	DnsServerIpAddressesOverride []json.RawMessage `json:"dnsServerIpAddressesOverride,omitempty"`
	// Additional host IP subnets assigned to this VLAN.
	AdditionalHostIpSubnets []json.RawMessage `json:"additionalHostIpSubnets,omitempty"`
	// ID of the WAN interface from which the prefix is delegated.
	PrefixDelegationWanInterfaceId string `json:"prefixDelegationWanInterfaceId,omitempty"`
}

// CreateNetworkIpv4ConfigurationDhcpConfiguration represents a nested object structure.
type CreateNetworkIpv4ConfigurationDhcpConfiguration struct {
	Mode           string                                                         `json:"mode"`
	IpAddressRange *CreateNetworkIpv4ConfigurationDhcpConfigurationIpAddressRange `json:"ipAddressRange,omitempty"`
	// Gateway IP address provided to DHCP clients. If null, the default gateway wil...
	GatewayIpAddressOverride string `json:"gatewayIpAddressOverride,omitempty"`
	// List of DNS servers assigned to client devices by the DHCP server. If none ar...
	DnsServerIpAddressesOverride []json.RawMessage `json:"dnsServerIpAddressesOverride,omitempty"`
	// The lease time in seconds for addresses in this range.
	LeaseTimeSeconds int64 `json:"leaseTimeSeconds,omitempty"`
	// Domain name that can be used to access network in the browser.
	DomainName string `json:"domainName,omitempty"`
}

// CreateNetworkIpv6ConfigurationClientAddressAssignment represents a nested object structure.
type CreateNetworkIpv6ConfigurationClientAddressAssignment struct {
	// IPv6 DHCP configuration for this network. At least one addressing method must...
	DhcpConfiguration *CreateNetworkIpv6ConfigurationClientAddressAssignmentDhcpConfiguration `json:"dhcpConfiguration,omitempty"`
	// Allows devices to obtain IPv6 addresses via SLAAC (Stateless Address Autoconf...
	SlaacEnabled bool `json:"slaacEnabled"`
}

// CreateNetworkIpv6ConfigurationClientAddressAssignmentDhcpConfigurationIpAddressSuffixRange represents a nested object structure.
type CreateNetworkIpv6ConfigurationClientAddressAssignmentDhcpConfigurationIpAddressSuffixRange struct {
	// Start suffix of the DHCPv6 address pool.
	Start string `json:"start"`
	// End suffix of the DHCPv6 address pool.
	Stop string `json:"stop"`
}

// CreateNetworkIpv6ConfigurationClientAddressAssignmentDhcpConfiguration represents a nested object structure.
type CreateNetworkIpv6ConfigurationClientAddressAssignmentDhcpConfiguration struct {
	IpAddressSuffixRange *CreateNetworkIpv6ConfigurationClientAddressAssignmentDhcpConfigurationIpAddressSuffixRange `json:"ipAddressSuffixRange"`
	// The lease time in seconds for IP addresses in this range.
	LeaseTimeSeconds int64 `json:"leaseTimeSeconds"`
}

// CreateNetworkIpv6ConfigurationRouterAdvertisement represents a nested object structure.
type CreateNetworkIpv6ConfigurationRouterAdvertisement struct {
	// Router advertisement priority.
	Priority string `json:"priority"`
}

// CreateNetworkManagement represents the management enum values.
type CreateNetworkManagement string

const (
	CreateNetworkManagementUnmanaged CreateNetworkManagement = "UNMANAGED"
	CreateNetworkManagementGateway   CreateNetworkManagement = "GATEWAY"
	CreateNetworkManagementSwitch    CreateNetworkManagement = "SWITCH"
)

type CreateNetworkVariantEnvelope struct {
	Management string `json:"management"`
}

// DecodeCreateNetworkResponse decodes a variant response based on the management field.
func DecodeCreateNetworkResponse(data []byte) (any, error) {
	var env CreateNetworkVariantEnvelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}

	switch env.Management {
	case "GATEWAY":
		var out CreateNetworkResponseGateway
		return &out, json.Unmarshal(data, &out)
	case "SWITCH":
		var out CreateNetworkResponseSwitch
		return &out, json.Unmarshal(data, &out)
	case "UNMANAGED":
		var out CreateNetworkResponseUnmanaged
		return &out, json.Unmarshal(data, &out)
	default:
		return nil, fmt.Errorf("unknown management value: %s", env.Management)
	}
}
