// Code generated by typegen. DO NOT EDIT.
// Endpoint: Create Network
// Method: POST /v1/sites/{siteId}/networks

package networks

import (
	"encoding/json"
)

// CreateNetworkPathParams contains the path parameters for the CreateNetwork endpoint.
type CreateNetworkPathParams struct {
	SiteId string `json:"siteId"`
}

// CreateNetworkRequest contains the request body for the CreateNetwork endpoint.
type CreateNetworkRequest struct {
	Management string `json:"management"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *CreateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// CreateNetworkResponse contains the response body from the CreateNetwork endpoint.
type CreateNetworkResponse struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *CreateNetworkMetadata `json:"metadata"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *CreateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// CreateNetworkDhcpGuarding represents a nested object structure.
type CreateNetworkDhcpGuarding struct {
	// List of trusted DHCP server IP addresses.
	TrustedDhcpServerIpAddresses []json.RawMessage `json:"trustedDhcpServerIpAddresses"`
}

// CreateNetworkMetadata represents a nested object structure.
type CreateNetworkMetadata struct {
	Origin string `json:"origin"`
}

// CreateNetworkManagement represents the management enum values.
type CreateNetworkManagement string

const (
	CreateNetworkManagementUnmanaged CreateNetworkManagement = "UNMANAGED"
	CreateNetworkManagementGateway   CreateNetworkManagement = "GATEWAY"
	CreateNetworkManagementSwitch    CreateNetworkManagement = "SWITCH"
)
