// Code generated by typegen. DO NOT EDIT.
// Endpoint: Delete Network
// Method: DELETE /v1/sites/{siteId}/networks/{networkId}

package networks

// DeleteNetworkPathParams contains the path parameters for the DeleteNetwork endpoint.
type DeleteNetworkPathParams struct {
	NetworkId string `json:"networkId"`
	SiteId    string `json:"siteId"`
}

// DeleteNetworkResponse represents the API response for Delete Network.
type DeleteNetworkResponse struct{}
