// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Network Details
// Method: GET /v1/sites/{siteId}/networks/{networkId}

package networks

import (
	"encoding/json"
)

// GetNetworkDetailsPathParams contains the path parameters for the GetNetworkDetails endpoint.
type GetNetworkDetailsPathParams struct {
	NetworkId string `json:"networkId"`
	SiteId    string `json:"siteId"`
}

// GetNetworkDetailsResponse contains the response body from the GetNetworkDetails endpoint.
type GetNetworkDetailsResponse struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *GetNetworkDetailsMetadata `json:"metadata"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *GetNetworkDetailsDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// GetNetworkDetailsMetadata represents a nested object structure.
type GetNetworkDetailsMetadata struct {
	Origin string `json:"origin"`
}

// GetNetworkDetailsDhcpGuarding represents a nested object structure.
type GetNetworkDetailsDhcpGuarding struct {
	// List of trusted DHCP server IP addresses.
	TrustedDhcpServerIpAddresses []json.RawMessage `json:"trustedDhcpServerIpAddresses"`
}
