// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Network Details
// Method: GET /v1/sites/{siteId}/networks/{networkId}

package networks

import (
	"encoding/json"
	"fmt"
)

// GetNetworkDetailsPathParams contains the path parameters for the GetNetworkDetails endpoint.
type GetNetworkDetailsPathParams struct {
	NetworkId string `json:"networkId"`
	SiteId    string `json:"siteId"`
}

// GetNetworkDetailsResponseGateway represents a nested object structure.
type GetNetworkDetailsResponseGateway struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *GetNetworkDetailsMetadata `json:"metadata"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *GetNetworkDetailsDhcpGuarding `json:"dhcpGuarding,omitempty"`
	// Whether this network is isolated from all other networks.
	IsolationEnabled bool `json:"isolationEnabled,omitempty"`
	// Whether this network is allowed to use cellular data when WAN connection(s) a...
	CellularBackupEnabled bool `json:"cellularBackupEnabled,omitempty"`
	// Firewall zone ID associated with this Network.
	ZoneId string `json:"zoneId,omitempty"`
	// Whether the internet access is allowed for the device on this network.
	InternetAccessEnabled bool `json:"internetAccessEnabled,omitempty"`
	// Whether this network should participate in mDNS traffic forwarding.
	MdnsForwardingEnabled bool `json:"mdnsForwardingEnabled,omitempty"`
	// Details about IPv4 configuration for this Network.
	Ipv4Configuration *GetNetworkDetailsIpv4Configuration `json:"ipv4Configuration,omitempty"`
	// Details about IPv6 configuration for this Network. If this field is omitted o...
	Ipv6Configuration *GetNetworkDetailsIpv6Configuration `json:"ipv6Configuration,omitempty"`
}

// GetNetworkDetailsResponseSwitch represents a nested object structure.
type GetNetworkDetailsResponseSwitch struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *GetNetworkDetailsMetadata `json:"metadata"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *GetNetworkDetailsDhcpGuarding `json:"dhcpGuarding,omitempty"`
	// Whether this network is isolated from all other networks.
	IsolationEnabled bool `json:"isolationEnabled,omitempty"`
	// Whether this network is allowed to use cellular data when WAN connection(s) a...
	CellularBackupEnabled bool `json:"cellularBackupEnabled,omitempty"`
	// ID of the L3 switching capable device that manages this network.
	DeviceId string `json:"deviceId,omitempty"`
	// Details about IPv4 configuration for this Network.
	Ipv4Configuration *GetNetworkDetailsIpv4Configuration `json:"ipv4Configuration,omitempty"`
}

// GetNetworkDetailsResponseUnmanaged represents a nested object structure.
type GetNetworkDetailsResponseUnmanaged struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *GetNetworkDetailsMetadata `json:"metadata"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *GetNetworkDetailsDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// GetNetworkDetailsIpv4Configuration represents a nested object structure.
type GetNetworkDetailsIpv4Configuration struct {
	// Whether the Network can automatically scale its subnet size based on the numb...
	AutoScaleEnabled bool   `json:"autoScaleEnabled"`
	HostIpAddress    string `json:"hostIpAddress"`
	PrefixLength     int64  `json:"prefixLength"`
	// Additional host IP subnets assigned to this VLAN.
	AdditionalHostIpSubnets []json.RawMessage `json:"additionalHostIpSubnets,omitempty"`
	// IPv4 DHCP configuration for this network. If this field is omitted or null, D...
	DhcpConfiguration *GetNetworkDetailsIpv4ConfigurationDhcpConfiguration `json:"dhcpConfiguration,omitempty"`
}

// GetNetworkDetailsMetadata represents a nested object structure.
type GetNetworkDetailsMetadata struct {
	Origin string `json:"origin"`
}

// GetNetworkDetailsDhcpGuarding represents a nested object structure.
type GetNetworkDetailsDhcpGuarding struct {
	// List of trusted DHCP server IP addresses.
	TrustedDhcpServerIpAddresses []json.RawMessage `json:"trustedDhcpServerIpAddresses"`
}

// GetNetworkDetailsIpv4ConfigurationDhcpConfiguration represents a nested object structure.
type GetNetworkDetailsIpv4ConfigurationDhcpConfiguration struct {
	Mode           string                                                             `json:"mode"`
	IpAddressRange *GetNetworkDetailsIpv4ConfigurationDhcpConfigurationIpAddressRange `json:"ipAddressRange,omitempty"`
	// Gateway IP address provided to DHCP clients. If null, the default gateway wil...
	GatewayIpAddressOverride string `json:"gatewayIpAddressOverride,omitempty"`
	// List of DNS servers assigned to client devices by the DHCP server. If none ar...
	DnsServerIpAddressesOverride []json.RawMessage `json:"dnsServerIpAddressesOverride,omitempty"`
	// The lease time in seconds for addresses in this range.
	LeaseTimeSeconds int64 `json:"leaseTimeSeconds,omitempty"`
	// Domain name that can be used to access network in the browser.
	DomainName string `json:"domainName,omitempty"`
}

// GetNetworkDetailsIpv4ConfigurationDhcpConfigurationIpAddressRange represents a nested object structure.
type GetNetworkDetailsIpv4ConfigurationDhcpConfigurationIpAddressRange struct {
	Start string `json:"start"`
	Stop  string `json:"stop"`
}

// GetNetworkDetailsIpv4ConfigurationDhcpConfigurationPxeConfiguration represents a nested object structure.
type GetNetworkDetailsIpv4ConfigurationDhcpConfigurationPxeConfiguration struct {
	ServerIpAddress string `json:"serverIpAddress"`
	Filename        string `json:"filename"`
}

// GetNetworkDetailsIpv6Configuration represents a nested object structure.
type GetNetworkDetailsIpv6Configuration struct {
	InterfaceType string `json:"interfaceType"`
	// Client Address Assignment
	ClientAddressAssignment *GetNetworkDetailsIpv6ConfigurationClientAddressAssignment `json:"clientAddressAssignment"`
	// Router advertisement. Without it, hosts will not autoconfigure addresses and ...
	RouterAdvertisement *GetNetworkDetailsIpv6ConfigurationRouterAdvertisement `json:"routerAdvertisement,omitempty"`
	// The IPv6 DNS server addresses assigned to this Network. If none are specified...
	DnsServerIpAddressesOverride []json.RawMessage `json:"dnsServerIpAddressesOverride,omitempty"`
	// Additional host IP subnets assigned to this VLAN.
	AdditionalHostIpSubnets []json.RawMessage `json:"additionalHostIpSubnets,omitempty"`
	// ID of the WAN interface from which the prefix is delegated.
	PrefixDelegationWanInterfaceId string `json:"prefixDelegationWanInterfaceId,omitempty"`
}

// GetNetworkDetailsIpv6ConfigurationClientAddressAssignmentDhcpConfigurationIpAddressSuffixRange represents a nested object structure.
type GetNetworkDetailsIpv6ConfigurationClientAddressAssignmentDhcpConfigurationIpAddressSuffixRange struct {
	// Start suffix of the DHCPv6 address pool.
	Start string `json:"start"`
	// End suffix of the DHCPv6 address pool.
	Stop string `json:"stop"`
}

// GetNetworkDetailsIpv4ConfigurationNatOutboundIpAddressConfiguration represents a nested object structure.
type GetNetworkDetailsIpv4ConfigurationNatOutboundIpAddressConfiguration struct {
	Type           string `json:"type"`
	WanInterfaceId string `json:"wanInterfaceId"`
	// IP address selection mode which determines how the IP address will be selecte...
	IpAddressSelectionMode string `json:"ipAddressSelectionMode,omitempty"`
}

// GetNetworkDetailsIpv6ConfigurationClientAddressAssignment represents a nested object structure.
type GetNetworkDetailsIpv6ConfigurationClientAddressAssignment struct {
	// IPv6 DHCP configuration for this network. At least one addressing method must...
	DhcpConfiguration *GetNetworkDetailsIpv6ConfigurationClientAddressAssignmentDhcpConfiguration `json:"dhcpConfiguration,omitempty"`
	// Allows devices to obtain IPv6 addresses via SLAAC (Stateless Address Autoconf...
	SlaacEnabled bool `json:"slaacEnabled"`
}

// GetNetworkDetailsIpv6ConfigurationClientAddressAssignmentDhcpConfiguration represents a nested object structure.
type GetNetworkDetailsIpv6ConfigurationClientAddressAssignmentDhcpConfiguration struct {
	IpAddressSuffixRange *GetNetworkDetailsIpv6ConfigurationClientAddressAssignmentDhcpConfigurationIpAddressSuffixRange `json:"ipAddressSuffixRange"`
	// The lease time in seconds for IP addresses in this range.
	LeaseTimeSeconds int64 `json:"leaseTimeSeconds"`
}

// GetNetworkDetailsIpv6ConfigurationRouterAdvertisement represents a nested object structure.
type GetNetworkDetailsIpv6ConfigurationRouterAdvertisement struct {
	// Router advertisement priority.
	Priority string `json:"priority"`
}

type GetNetworkDetailsVariantEnvelope struct {
	Management string `json:"management"`
}

// DecodeGetNetworkDetailsResponse decodes a variant response based on the management field.
func DecodeGetNetworkDetailsResponse(data []byte) (any, error) {
	var env GetNetworkDetailsVariantEnvelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}

	switch env.Management {
	case "GATEWAY":
		var out GetNetworkDetailsResponseGateway
		return &out, json.Unmarshal(data, &out)
	case "SWITCH":
		var out GetNetworkDetailsResponseSwitch
		return &out, json.Unmarshal(data, &out)
	case "UNMANAGED":
		var out GetNetworkDetailsResponseUnmanaged
		return &out, json.Unmarshal(data, &out)
	default:
		return nil, fmt.Errorf("unknown management value: %s", env.Management)
	}
}
