// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Networks
// Method: GET /v1/sites/{siteId}/networks

package networks

// ListNetworksPathParams contains the path parameters for the ListNetworks endpoint.
type ListNetworksPathParams struct {
	SiteId string `json:"siteId"`
}

// ListNetworksResponse contains the response body from the ListNetworks endpoint.
type ListNetworksResponse struct {
	PaginatedResponse
	Data []ListNetworksData `json:"data"`
}

// ListNetworksData represents a nested object structure.
type ListNetworksData struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *ListNetworksDataMetadata `json:"metadata"`
}

// ListNetworksDataMetadata represents a nested object structure.
type ListNetworksDataMetadata struct {
	Origin string `json:"origin"`
}
