// Code generated by clientgen. DO NOT EDIT.

package networks

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Networks provides access to the Networks API.
type Networks struct {
	client *http.Client
}

// NewNetworks creates a new Networks instance.
func NewNetworks(client *http.Client) *Networks {
	return &Networks{
		client: client,
	}
}

// CreateNetwork calls the CreateNetwork endpoint.
// POST /v1/sites/{siteId}/networks
func (c *Networks) CreateNetwork(ctx context.Context, siteId string, req any) (any, error) {
	path := fmt.Sprintf("/v1/sites/%s/networks", siteId)
	var result any
	if err := c.client.Post(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// DeleteNetwork calls the DeleteNetwork endpoint.
// DELETE /v1/sites/{siteId}/networks/{networkId}
func (c *Networks) DeleteNetwork(ctx context.Context, networkId string, siteId string) (*DeleteNetworkResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/networks/%s", networkId, siteId)
	var result DeleteNetworkResponse
	if err := c.client.Delete(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetNetworkDetails calls the GetNetworkDetails endpoint.
// GET /v1/sites/{siteId}/networks/{networkId}
func (c *Networks) GetNetworkDetails(ctx context.Context, networkId string, siteId string) (any, error) {
	path := fmt.Sprintf("/v1/sites/%s/networks/%s", networkId, siteId)
	var result any
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// ListNetworks calls the ListNetworks endpoint.
// GET /v1/sites/{siteId}/networks
func (c *Networks) ListNetworks(ctx context.Context, siteId string) (*ListNetworksResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/networks", siteId)
	var result ListNetworksResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateNetwork calls the UpdateNetwork endpoint.
// PUT /v1/sites/{siteId}/networks/{networkId}
func (c *Networks) UpdateNetwork(ctx context.Context, networkId string, siteId string, req any) (any, error) {
	path := fmt.Sprintf("/v1/sites/%s/networks/%s", networkId, siteId)
	var result any
	if err := c.client.Put(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return result, nil
}
