// Code generated by typegen. DO NOT EDIT.
// Endpoint: Update Network
// Method: PUT /v1/sites/{siteId}/networks/{networkId}

package networks

import (
	"encoding/json"
	"fmt"
)

// UpdateNetworkPathParams contains the path parameters for the UpdateNetwork endpoint.
type UpdateNetworkPathParams struct {
	NetworkId string `json:"networkId"`
	SiteId    string `json:"siteId"`
}

// UpdateNetworkRequestGateway represents a nested object structure.
type UpdateNetworkRequestGateway struct {
	Management string `json:"management"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *UpdateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
	// Whether this network is isolated from all other networks.
	IsolationEnabled bool `json:"isolationEnabled,omitempty"`
	// Whether this network is allowed to use cellular data when WAN connection(s) a...
	CellularBackupEnabled bool `json:"cellularBackupEnabled,omitempty"`
	// Firewall zone ID associated with this Network.
	ZoneId string `json:"zoneId,omitempty"`
	// Whether the internet access is allowed for the device on this network.
	InternetAccessEnabled bool `json:"internetAccessEnabled,omitempty"`
	// Whether this network should participate in mDNS traffic forwarding.
	MdnsForwardingEnabled bool `json:"mdnsForwardingEnabled,omitempty"`
	// Details about IPv4 configuration for this Network.
	Ipv4Configuration *UpdateNetworkIpv4Configuration `json:"ipv4Configuration,omitempty"`
	// Details about IPv6 configuration for this Network. If this field is omitted o...
	Ipv6Configuration *UpdateNetworkIpv6Configuration `json:"ipv6Configuration,omitempty"`
}

// UpdateNetworkRequestSwitch represents a nested object structure.
type UpdateNetworkRequestSwitch struct {
	Management string `json:"management"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *UpdateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
	// Whether this network is isolated from all other networks.
	IsolationEnabled bool `json:"isolationEnabled,omitempty"`
	// Whether this network is allowed to use cellular data when WAN connection(s) a...
	CellularBackupEnabled bool `json:"cellularBackupEnabled,omitempty"`
	// ID of the L3 switching capable device that manages this network.
	DeviceId string `json:"deviceId,omitempty"`
	// Details about IPv4 configuration for this Network.
	Ipv4Configuration *UpdateNetworkIpv4Configuration `json:"ipv4Configuration,omitempty"`
}

// UpdateNetworkRequestUnmanaged represents a nested object structure.
type UpdateNetworkRequestUnmanaged struct {
	Management string `json:"management"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *UpdateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// UpdateNetworkResponseGateway represents a nested object structure.
type UpdateNetworkResponseGateway struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *UpdateNetworkMetadata `json:"metadata"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *UpdateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// UpdateNetworkResponseSwitch represents a nested object structure.
type UpdateNetworkResponseSwitch struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *UpdateNetworkMetadata `json:"metadata"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *UpdateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// UpdateNetworkResponseUnmanaged represents a nested object structure.
type UpdateNetworkResponseUnmanaged struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *UpdateNetworkMetadata `json:"metadata"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *UpdateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// UpdateNetworkIpv4ConfigurationDhcpConfigurationIpAddressRange represents a nested object structure.
type UpdateNetworkIpv4ConfigurationDhcpConfigurationIpAddressRange struct {
	Start string `json:"start"`
	Stop  string `json:"stop"`
}

// UpdateNetworkDhcpGuarding represents a nested object structure.
type UpdateNetworkDhcpGuarding struct {
	// List of trusted DHCP server IP addresses.
	TrustedDhcpServerIpAddresses []json.RawMessage `json:"trustedDhcpServerIpAddresses"`
}

// UpdateNetworkIpv6ConfigurationClientAddressAssignment represents a nested object structure.
type UpdateNetworkIpv6ConfigurationClientAddressAssignment struct {
	// IPv6 DHCP configuration for this network. At least one addressing method must...
	DhcpConfiguration *UpdateNetworkIpv6ConfigurationClientAddressAssignmentDhcpConfiguration `json:"dhcpConfiguration,omitempty"`
	// Allows devices to obtain IPv6 addresses via SLAAC (Stateless Address Autoconf...
	SlaacEnabled bool `json:"slaacEnabled"`
}

// UpdateNetworkIpv6ConfigurationRouterAdvertisement represents a nested object structure.
type UpdateNetworkIpv6ConfigurationRouterAdvertisement struct {
	// Router advertisement priority.
	Priority string `json:"priority"`
}

// UpdateNetworkIpv4Configuration represents a nested object structure.
type UpdateNetworkIpv4Configuration struct {
	// Whether the Network can automatically scale its subnet size based on the numb...
	AutoScaleEnabled bool   `json:"autoScaleEnabled"`
	HostIpAddress    string `json:"hostIpAddress"`
	PrefixLength     int64  `json:"prefixLength"`
	// Additional host IP subnets assigned to this VLAN.
	AdditionalHostIpSubnets []json.RawMessage `json:"additionalHostIpSubnets,omitempty"`
	// IPv4 DHCP configuration for this network. If this field is omitted or null, D...
	DhcpConfiguration *UpdateNetworkIpv4ConfigurationDhcpConfiguration `json:"dhcpConfiguration,omitempty"`
}

// UpdateNetworkIpv4ConfigurationDhcpConfiguration represents a nested object structure.
type UpdateNetworkIpv4ConfigurationDhcpConfiguration struct {
	Mode           string                                                         `json:"mode"`
	IpAddressRange *UpdateNetworkIpv4ConfigurationDhcpConfigurationIpAddressRange `json:"ipAddressRange,omitempty"`
	// Gateway IP address provided to DHCP clients. If null, the default gateway wil...
	GatewayIpAddressOverride string `json:"gatewayIpAddressOverride,omitempty"`
	// List of DNS servers assigned to client devices by the DHCP server. If none ar...
	DnsServerIpAddressesOverride []json.RawMessage `json:"dnsServerIpAddressesOverride,omitempty"`
	// The lease time in seconds for addresses in this range.
	LeaseTimeSeconds int64 `json:"leaseTimeSeconds,omitempty"`
	// Domain name that can be used to access network in the browser.
	DomainName string `json:"domainName,omitempty"`
}

// UpdateNetworkMetadata represents a nested object structure.
type UpdateNetworkMetadata struct {
	Origin string `json:"origin"`
}

// UpdateNetworkIpv4ConfigurationNatOutboundIpAddressConfiguration represents a nested object structure.
type UpdateNetworkIpv4ConfigurationNatOutboundIpAddressConfiguration struct {
	Type           string `json:"type"`
	WanInterfaceId string `json:"wanInterfaceId"`
	// IP address selection mode which determines how the IP address will be selecte...
	IpAddressSelectionMode string `json:"ipAddressSelectionMode,omitempty"`
}

// UpdateNetworkIpv6ConfigurationClientAddressAssignmentDhcpConfiguration represents a nested object structure.
type UpdateNetworkIpv6ConfigurationClientAddressAssignmentDhcpConfiguration struct {
	IpAddressSuffixRange *UpdateNetworkIpv6ConfigurationClientAddressAssignmentDhcpConfigurationIpAddressSuffixRange `json:"ipAddressSuffixRange"`
	// The lease time in seconds for IP addresses in this range.
	LeaseTimeSeconds int64 `json:"leaseTimeSeconds"`
}

// UpdateNetworkIpv4ConfigurationDhcpConfigurationPxeConfiguration represents a nested object structure.
type UpdateNetworkIpv4ConfigurationDhcpConfigurationPxeConfiguration struct {
	ServerIpAddress string `json:"serverIpAddress"`
	Filename        string `json:"filename"`
}

// UpdateNetworkIpv6ConfigurationClientAddressAssignmentDhcpConfigurationIpAddressSuffixRange represents a nested object structure.
type UpdateNetworkIpv6ConfigurationClientAddressAssignmentDhcpConfigurationIpAddressSuffixRange struct {
	// Start suffix of the DHCPv6 address pool.
	Start string `json:"start"`
	// End suffix of the DHCPv6 address pool.
	Stop string `json:"stop"`
}

// UpdateNetworkIpv6Configuration represents a nested object structure.
type UpdateNetworkIpv6Configuration struct {
	InterfaceType string `json:"interfaceType"`
	// Client Address Assignment
	ClientAddressAssignment *UpdateNetworkIpv6ConfigurationClientAddressAssignment `json:"clientAddressAssignment"`
	// Router advertisement. Without it, hosts will not autoconfigure addresses and ...
	RouterAdvertisement *UpdateNetworkIpv6ConfigurationRouterAdvertisement `json:"routerAdvertisement,omitempty"`
	// The IPv6 DNS server addresses assigned to this Network. If none are specified...
	DnsServerIpAddressesOverride []json.RawMessage `json:"dnsServerIpAddressesOverride,omitempty"`
	// Additional host IP subnets assigned to this VLAN.
	AdditionalHostIpSubnets []json.RawMessage `json:"additionalHostIpSubnets,omitempty"`
	// ID of the WAN interface from which the prefix is delegated.
	PrefixDelegationWanInterfaceId string `json:"prefixDelegationWanInterfaceId,omitempty"`
}

// UpdateNetworkManagement represents the management enum values.
type UpdateNetworkManagement string

const (
	UpdateNetworkManagementUnmanaged UpdateNetworkManagement = "UNMANAGED"
	UpdateNetworkManagementGateway   UpdateNetworkManagement = "GATEWAY"
	UpdateNetworkManagementSwitch    UpdateNetworkManagement = "SWITCH"
)

type UpdateNetworkVariantEnvelope struct {
	Management string `json:"management"`
}

// DecodeUpdateNetworkResponse decodes a variant response based on the management field.
func DecodeUpdateNetworkResponse(data []byte) (any, error) {
	var env UpdateNetworkVariantEnvelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}

	switch env.Management {
	case "GATEWAY":
		var out UpdateNetworkResponseGateway
		return &out, json.Unmarshal(data, &out)
	case "SWITCH":
		var out UpdateNetworkResponseSwitch
		return &out, json.Unmarshal(data, &out)
	case "UNMANAGED":
		var out UpdateNetworkResponseUnmanaged
		return &out, json.Unmarshal(data, &out)
	default:
		return nil, fmt.Errorf("unknown management value: %s", env.Management)
	}
}
