// Code generated by typegen. DO NOT EDIT.
// Endpoint: Update Network
// Method: PUT /v1/sites/{siteId}/networks/{networkId}

package networks

import (
	"encoding/json"
)

// UpdateNetworkPathParams contains the path parameters for the UpdateNetwork endpoint.
type UpdateNetworkPathParams struct {
	NetworkId string `json:"networkId"`
	SiteId    string `json:"siteId"`
}

// UpdateNetworkRequest contains the request body for the UpdateNetwork endpoint.
type UpdateNetworkRequest struct {
	Management string `json:"management"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *UpdateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// UpdateNetworkResponse contains the response body from the UpdateNetwork endpoint.
type UpdateNetworkResponse struct {
	Management string `json:"management"`
	Id         string `json:"id"`
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	VlanId     int64  `json:"vlanId"`
	// Orchestrated or System-defined configurable network support
	Metadata *UpdateNetworkMetadata `json:"metadata"`
	// DHCP Guarding settings for this Network. If this field is omitted or null, th...
	DhcpGuarding *UpdateNetworkDhcpGuarding `json:"dhcpGuarding,omitempty"`
}

// UpdateNetworkDhcpGuarding represents a nested object structure.
type UpdateNetworkDhcpGuarding struct {
	// List of trusted DHCP server IP addresses.
	TrustedDhcpServerIpAddresses []json.RawMessage `json:"trustedDhcpServerIpAddresses"`
}

// UpdateNetworkMetadata represents a nested object structure.
type UpdateNetworkMetadata struct {
	Origin string `json:"origin"`
}

// UpdateNetworkManagement represents the management enum values.
type UpdateNetworkManagement string

const (
	UpdateNetworkManagementUnmanaged UpdateNetworkManagement = "UNMANAGED"
	UpdateNetworkManagementGateway   UpdateNetworkManagement = "GATEWAY"
	UpdateNetworkManagementSwitch    UpdateNetworkManagement = "SWITCH"
)
