// Code generated by clientgen. DO NOT EDIT.

package broadcasts

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Broadcasts provides access to the Broadcasts API.
type Broadcasts struct {
	client *http.Client
}

// NewBroadcasts creates a new Broadcasts instance.
func NewBroadcasts(client *http.Client) *Broadcasts {
	return &Broadcasts{
		client: client,
	}
}

// CreateWifiBroadcast calls the CreateWifiBroadcast endpoint.
// POST /v1/sites/{siteId}/wifi/broadcasts
func (c *Broadcasts) CreateWifiBroadcast(ctx context.Context, siteId string, req any) (any, error) {
	path := fmt.Sprintf("/v1/sites/%s/wifi/broadcasts", siteId)
	var result any
	if err := c.client.Post(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// DeleteWifiBroadcast calls the DeleteWifiBroadcast endpoint.
// DELETE /v1/sites/{siteId}/wifi/broadcasts/{wifiBroadcastId}
func (c *Broadcasts) DeleteWifiBroadcast(ctx context.Context, wifiBroadcastId string, siteId string) (*DeleteWifiBroadcastResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/wifi/broadcasts/%s", wifiBroadcastId, siteId)
	var result DeleteWifiBroadcastResponse
	if err := c.client.Delete(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetWifiBroadcastDetails calls the GetWifiBroadcastDetails endpoint.
// GET /v1/sites/{siteId}/wifi/broadcasts/{wifiBroadcastId}
func (c *Broadcasts) GetWifiBroadcastDetails(ctx context.Context, wifiBroadcastId string, siteId string) (any, error) {
	path := fmt.Sprintf("/v1/sites/%s/wifi/broadcasts/%s", wifiBroadcastId, siteId)
	var result any
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// ListWifiBroadcasts calls the ListWifiBroadcasts endpoint.
// GET /v1/sites/{siteId}/wifi/broadcasts
func (c *Broadcasts) ListWifiBroadcasts(ctx context.Context, siteId string) (*ListWifiBroadcastsResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/wifi/broadcasts", siteId)
	var result ListWifiBroadcastsResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateWifiBroadcast calls the UpdateWifiBroadcast endpoint.
// PUT /v1/sites/{siteId}/wifi/broadcasts/{wifiBroadcastId}
func (c *Broadcasts) UpdateWifiBroadcast(ctx context.Context, wifiBroadcastId string, siteId string, req any) (any, error) {
	path := fmt.Sprintf("/v1/sites/%s/wifi/broadcasts/%s", wifiBroadcastId, siteId)
	var result any
	if err := c.client.Put(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return result, nil
}
