// Code generated by typegen. DO NOT EDIT.
// Endpoint: Create Wifi Broadcast
// Method: POST /v1/sites/{siteId}/wifi/broadcasts

package broadcasts

import (
	"encoding/json"
	"fmt"
	"time"
)

// CreateWifiBroadcastPathParams contains the path parameters for the CreateWifiBroadcast endpoint.
type CreateWifiBroadcastPathParams struct {
	SiteId string `json:"siteId"`
}

// CreateWifiBroadcastRequestIotOptimized represents a nested object structure.
type CreateWifiBroadcastRequestIotOptimized struct {
	Type                  string                                    `json:"type"`
	Name                  string                                    `json:"name"`
	Network               *ClientAccess                             `json:"network,omitempty"`
	Enabled               bool                                      `json:"enabled"`
	SecurityConfiguration *CreateWifiBroadcastSecurityConfiguration `json:"securityConfiguration"`
	// Defines the custom scope of devices that will broadcast this WiFi network. If...
	BroadcastingDeviceFilter            *CreateWifiBroadcastBroadcastingDeviceFilter `json:"broadcastingDeviceFilter,omitempty"`
	MdnsProxyConfiguration              *CreateWifiBroadcastMdnsProxyConfiguration   `json:"mdnsProxyConfiguration,omitempty"`
	MulticastFilteringPolicy            *CreateWifiBroadcastMulticastFilteringPolicy `json:"multicastFilteringPolicy,omitempty"`
	MulticastToUnicastConversionEnabled bool                                         `json:"multicastToUnicastConversionEnabled"`
	ClientIsolationEnabled              bool                                         `json:"clientIsolationEnabled"`
	HideName                            bool                                         `json:"hideName"`
	// Indicates whether Unscheduled Automatic Power Save Delivery (U-APSD) is enabled
	UapsdEnabled                    bool                                                `json:"uapsdEnabled"`
	BasicDataRateKbpsByFrequencyGHz *CreateWifiBroadcastBasicDataRateKbpsByFrequencyGHz `json:"basicDataRateKbpsByFrequencyGHz,omitempty"`
	// Client connection filtering policy. Allow/restrict access to the WiFi network...
	ClientFilteringPolicy         *CreateWifiBroadcastClientFilteringPolicy         `json:"clientFilteringPolicy,omitempty"`
	BlackoutScheduleConfiguration *CreateWifiBroadcastBlackoutScheduleConfiguration `json:"blackoutScheduleConfiguration,omitempty"`
}

// CreateWifiBroadcastRequestStandard represents a nested object structure.
type CreateWifiBroadcastRequestStandard struct {
	Type                  string                                    `json:"type"`
	Name                  string                                    `json:"name"`
	Network               *ClientAccess                             `json:"network,omitempty"`
	Enabled               bool                                      `json:"enabled"`
	SecurityConfiguration *CreateWifiBroadcastSecurityConfiguration `json:"securityConfiguration"`
	// Defines the custom scope of devices that will broadcast this WiFi network. If...
	BroadcastingDeviceFilter            *CreateWifiBroadcastBroadcastingDeviceFilter `json:"broadcastingDeviceFilter,omitempty"`
	MdnsProxyConfiguration              *CreateWifiBroadcastMdnsProxyConfiguration   `json:"mdnsProxyConfiguration,omitempty"`
	MulticastFilteringPolicy            *CreateWifiBroadcastMulticastFilteringPolicy `json:"multicastFilteringPolicy,omitempty"`
	MulticastToUnicastConversionEnabled bool                                         `json:"multicastToUnicastConversionEnabled"`
	ClientIsolationEnabled              bool                                         `json:"clientIsolationEnabled"`
	HideName                            bool                                         `json:"hideName"`
	// Indicates whether Unscheduled Automatic Power Save Delivery (U-APSD) is enabled
	UapsdEnabled                    bool                                                `json:"uapsdEnabled"`
	BasicDataRateKbpsByFrequencyGHz *CreateWifiBroadcastBasicDataRateKbpsByFrequencyGHz `json:"basicDataRateKbpsByFrequencyGHz,omitempty"`
	// Client connection filtering policy. Allow/restrict access to the WiFi network...
	ClientFilteringPolicy            *CreateWifiBroadcastClientFilteringPolicy            `json:"clientFilteringPolicy,omitempty"`
	BlackoutScheduleConfiguration    *CreateWifiBroadcastBlackoutScheduleConfiguration    `json:"blackoutScheduleConfiguration,omitempty"`
	BroadcastingFrequenciesGHz       []json.RawMessage                                    `json:"broadcastingFrequenciesGHz,omitempty"`
	HotspotConfiguration             *ClientAccess                                        `json:"hotspotConfiguration,omitempty"`
	MloEnabled                       bool                                                 `json:"mloEnabled,omitempty"`
	BandSteeringEnabled              bool                                                 `json:"bandSteeringEnabled,omitempty"`
	ArpProxyEnabled                  bool                                                 `json:"arpProxyEnabled,omitempty"`
	BssTransitionEnabled             bool                                                 `json:"bssTransitionEnabled,omitempty"`
	DtimPeriodByFrequencyGHzOverride *CreateWifiBroadcastDtimPeriodByFrequencyGHzOverride `json:"dtimPeriodByFrequencyGHzOverride,omitempty"`
}

// CreateWifiBroadcastResponseIotOptimized represents a nested object structure.
type CreateWifiBroadcastResponseIotOptimized struct {
	Type                  string                                    `json:"type"`
	Id                    string                                    `json:"id"`
	Name                  string                                    `json:"name"`
	Metadata              *CreateWifiBroadcastMetadata              `json:"metadata"`
	Enabled               bool                                      `json:"enabled"`
	Network               *ClientAccess                             `json:"network,omitempty"`
	SecurityConfiguration *CreateWifiBroadcastSecurityConfiguration `json:"securityConfiguration"`
	// Defines the custom scope of devices that will broadcast this WiFi network. If...
	BroadcastingDeviceFilter            *CreateWifiBroadcastBroadcastingDeviceFilter `json:"broadcastingDeviceFilter,omitempty"`
	MdnsProxyConfiguration              *CreateWifiBroadcastMdnsProxyConfiguration   `json:"mdnsProxyConfiguration,omitempty"`
	MulticastFilteringPolicy            *CreateWifiBroadcastMulticastFilteringPolicy `json:"multicastFilteringPolicy,omitempty"`
	MulticastToUnicastConversionEnabled bool                                         `json:"multicastToUnicastConversionEnabled"`
	ClientIsolationEnabled              bool                                         `json:"clientIsolationEnabled"`
	HideName                            bool                                         `json:"hideName"`
	// Indicates whether Unscheduled Automatic Power Save Delivery (U-APSD) is enabled
	UapsdEnabled                    bool                                                `json:"uapsdEnabled"`
	BasicDataRateKbpsByFrequencyGHz *CreateWifiBroadcastBasicDataRateKbpsByFrequencyGHz `json:"basicDataRateKbpsByFrequencyGHz,omitempty"`
	// Client connection filtering policy. Allow/restrict access to the WiFi network...
	ClientFilteringPolicy            *CreateWifiBroadcastClientFilteringPolicy            `json:"clientFilteringPolicy,omitempty"`
	BlackoutScheduleConfiguration    *CreateWifiBroadcastBlackoutScheduleConfiguration    `json:"blackoutScheduleConfiguration,omitempty"`
	BroadcastingFrequenciesGHz       []json.RawMessage                                    `json:"broadcastingFrequenciesGHz,omitempty"`
	HotspotConfiguration             *ClientAccess                                        `json:"hotspotConfiguration,omitempty"`
	MloEnabled                       bool                                                 `json:"mloEnabled,omitempty"`
	BandSteeringEnabled              bool                                                 `json:"bandSteeringEnabled,omitempty"`
	ArpProxyEnabled                  bool                                                 `json:"arpProxyEnabled,omitempty"`
	BssTransitionEnabled             bool                                                 `json:"bssTransitionEnabled,omitempty"`
	DtimPeriodByFrequencyGHzOverride *CreateWifiBroadcastDtimPeriodByFrequencyGHzOverride `json:"dtimPeriodByFrequencyGHzOverride,omitempty"`
}

// CreateWifiBroadcastResponseStandard represents a nested object structure.
type CreateWifiBroadcastResponseStandard struct {
	Type                  string                                    `json:"type"`
	Id                    string                                    `json:"id"`
	Name                  string                                    `json:"name"`
	Metadata              *CreateWifiBroadcastMetadata              `json:"metadata"`
	Enabled               bool                                      `json:"enabled"`
	Network               *ClientAccess                             `json:"network,omitempty"`
	SecurityConfiguration *CreateWifiBroadcastSecurityConfiguration `json:"securityConfiguration"`
	// Defines the custom scope of devices that will broadcast this WiFi network. If...
	BroadcastingDeviceFilter            *CreateWifiBroadcastBroadcastingDeviceFilter `json:"broadcastingDeviceFilter,omitempty"`
	MdnsProxyConfiguration              *CreateWifiBroadcastMdnsProxyConfiguration   `json:"mdnsProxyConfiguration,omitempty"`
	MulticastFilteringPolicy            *CreateWifiBroadcastMulticastFilteringPolicy `json:"multicastFilteringPolicy,omitempty"`
	MulticastToUnicastConversionEnabled bool                                         `json:"multicastToUnicastConversionEnabled"`
	ClientIsolationEnabled              bool                                         `json:"clientIsolationEnabled"`
	HideName                            bool                                         `json:"hideName"`
	// Indicates whether Unscheduled Automatic Power Save Delivery (U-APSD) is enabled
	UapsdEnabled                    bool                                                `json:"uapsdEnabled"`
	BasicDataRateKbpsByFrequencyGHz *CreateWifiBroadcastBasicDataRateKbpsByFrequencyGHz `json:"basicDataRateKbpsByFrequencyGHz,omitempty"`
	// Client connection filtering policy. Allow/restrict access to the WiFi network...
	ClientFilteringPolicy            *CreateWifiBroadcastClientFilteringPolicy            `json:"clientFilteringPolicy,omitempty"`
	BlackoutScheduleConfiguration    *CreateWifiBroadcastBlackoutScheduleConfiguration    `json:"blackoutScheduleConfiguration,omitempty"`
	BroadcastingFrequenciesGHz       []json.RawMessage                                    `json:"broadcastingFrequenciesGHz,omitempty"`
	HotspotConfiguration             *ClientAccess                                        `json:"hotspotConfiguration,omitempty"`
	MloEnabled                       bool                                                 `json:"mloEnabled,omitempty"`
	BandSteeringEnabled              bool                                                 `json:"bandSteeringEnabled,omitempty"`
	ArpProxyEnabled                  bool                                                 `json:"arpProxyEnabled,omitempty"`
	BssTransitionEnabled             bool                                                 `json:"bssTransitionEnabled,omitempty"`
	DtimPeriodByFrequencyGHzOverride *CreateWifiBroadcastDtimPeriodByFrequencyGHzOverride `json:"dtimPeriodByFrequencyGHzOverride,omitempty"`
}

// CreateWifiBroadcastSecurityConfigurationRadiusConfigurationNasId represents a nested object structure.
type CreateWifiBroadcastSecurityConfigurationRadiusConfigurationNasId struct {
	Type   string `json:"type"`
	Source string `json:"source,omitempty"`
}

// CreateWifiBroadcastBlackoutScheduleConfigurationDays represents a nested object structure.
type CreateWifiBroadcastBlackoutScheduleConfigurationDays struct {
	Type string `json:"type"`
	Day  string `json:"day"`
}

// CreateWifiBroadcastMdnsProxyConfiguration represents a nested object structure.
type CreateWifiBroadcastMdnsProxyConfiguration struct {
	Mode string `json:"mode"`
}

// CreateWifiBroadcastSecurityConfiguration represents a nested object structure.
type CreateWifiBroadcastSecurityConfiguration struct {
	Type                string                                                       `json:"type"`
	RadiusConfiguration *CreateWifiBroadcastSecurityConfigurationRadiusConfiguration `json:"radiusConfiguration,omitempty"`
}

// CreateWifiBroadcastMetadata represents a nested object structure.
type CreateWifiBroadcastMetadata struct {
	Origin string `json:"origin"`
}

// CreateWifiBroadcastBasicDataRateKbpsByFrequencyGHz represents a nested object structure.
type CreateWifiBroadcastBasicDataRateKbpsByFrequencyGHz struct {
	N5  int64 `json:"5"`
	N24 int64 `json:"2.4"`
}

// CreateWifiBroadcastSecurityConfigurationRadiusConfiguration represents a nested object structure.
type CreateWifiBroadcastSecurityConfigurationRadiusConfiguration struct {
	ProfileId                      string                                                                                     `json:"profileId"`
	NasId                          *CreateWifiBroadcastSecurityConfigurationRadiusConfigurationNasId                          `json:"nasId"`
	MacAuthenticationConfiguration *CreateWifiBroadcastSecurityConfigurationRadiusConfigurationMacAuthenticationConfiguration `json:"macAuthenticationConfiguration"`
}

// CreateWifiBroadcastMulticastFilteringPolicy represents a nested object structure.
type CreateWifiBroadcastMulticastFilteringPolicy struct {
	Action string `json:"action"`
	// List of multicast source MAC addresses allowed. Multicast traffic from gatewa...
	SourceMacAddressFilter []json.RawMessage `json:"sourceMacAddressFilter,omitempty"`
}

// CreateWifiBroadcastClientFilteringPolicy represents a nested object structure.
type CreateWifiBroadcastClientFilteringPolicy struct {
	Action           string            `json:"action"`
	MacAddressFilter []json.RawMessage `json:"macAddressFilter"`
}

// CreateWifiBroadcastDtimPeriodByFrequencyGHzOverride represents a nested object structure.
type CreateWifiBroadcastDtimPeriodByFrequencyGHzOverride struct {
	N5  int64 `json:"5"`
	N6  int64 `json:"6"`
	N24 int64 `json:"2.4"`
}

// CreateWifiBroadcastSecurityConfigurationRadiusConfigurationMacAuthenticationConfiguration represents a nested object structure.
type CreateWifiBroadcastSecurityConfigurationRadiusConfigurationMacAuthenticationConfiguration struct {
	MacAddressFormat time.Time `json:"macAddressFormat"`
}

// CreateWifiBroadcastBroadcastingDeviceFilter represents a nested object structure.
type CreateWifiBroadcastBroadcastingDeviceFilter struct {
	Type string `json:"type"`
	// List of Access Point capable device IDs to which the WiFi broadcast applies.
	DeviceIds []json.RawMessage `json:"deviceIds,omitempty"`
}

// CreateWifiBroadcastBlackoutScheduleConfiguration represents a nested object structure.
type CreateWifiBroadcastBlackoutScheduleConfiguration struct {
	Days []CreateWifiBroadcastBlackoutScheduleConfigurationDays `json:"days"`
}

// CreateWifiBroadcastType represents the type enum values.
type CreateWifiBroadcastType string

const (
	CreateWifiBroadcastTypeStandard     CreateWifiBroadcastType = "STANDARD"
	CreateWifiBroadcastTypeIotOptimized CreateWifiBroadcastType = "IOT_OPTIMIZED"
)

type CreateWifiBroadcastVariantEnvelope struct {
	Type string `json:"type"`
}

// DecodeCreateWifiBroadcastResponse decodes a variant response based on the type field.
func DecodeCreateWifiBroadcastResponse(data []byte) (any, error) {
	var env CreateWifiBroadcastVariantEnvelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}

	switch env.Type {
	case "IOT_OPTIMIZED":
		var out CreateWifiBroadcastResponseIotOptimized
		return &out, json.Unmarshal(data, &out)
	case "STANDARD":
		var out CreateWifiBroadcastResponseStandard
		return &out, json.Unmarshal(data, &out)
	default:
		return nil, fmt.Errorf("unknown type value: %s", env.Type)
	}
}
