// Code generated by typegen. DO NOT EDIT.
// Endpoint: Delete Wifi Broadcast
// Method: DELETE /v1/sites/{siteId}/wifi/broadcasts/{wifiBroadcastId}

package broadcasts

// DeleteWifiBroadcastPathParams contains the path parameters for the DeleteWifiBroadcast endpoint.
type DeleteWifiBroadcastPathParams struct {
	WifiBroadcastId string `json:"wifiBroadcastId"`
	SiteId          string `json:"siteId"`
}

// DeleteWifiBroadcastResponse represents the API response for Delete Wifi Broadcast.
type DeleteWifiBroadcastResponse struct{}
