// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Wifi Broadcast Details
// Method: GET /v1/sites/{siteId}/wifi/broadcasts/{wifiBroadcastId}

package broadcasts

import (
	"encoding/json"
	"time"
)

// GetWifiBroadcastDetailsPathParams contains the path parameters for the GetWifiBroadcastDetails endpoint.
type GetWifiBroadcastDetailsPathParams struct {
	WifiBroadcastId string `json:"wifiBroadcastId"`
	SiteId          string `json:"siteId"`
}

// GetWifiBroadcastDetailsResponse contains the response body from the GetWifiBroadcastDetails endpoint.
type GetWifiBroadcastDetailsResponse struct {
	Type                  string                                        `json:"type"`
	Id                    string                                        `json:"id"`
	Name                  string                                        `json:"name"`
	Metadata              *GetWifiBroadcastDetailsMetadata              `json:"metadata"`
	Enabled               bool                                          `json:"enabled"`
	Network               *ClientAccess                                 `json:"network,omitempty"`
	SecurityConfiguration *GetWifiBroadcastDetailsSecurityConfiguration `json:"securityConfiguration"`
	// Defines the custom scope of devices that will broadcast this WiFi network. If...
	BroadcastingDeviceFilter            *GetWifiBroadcastDetailsBroadcastingDeviceFilter `json:"broadcastingDeviceFilter,omitempty"`
	MdnsProxyConfiguration              *GetWifiBroadcastDetailsMdnsProxyConfiguration   `json:"mdnsProxyConfiguration,omitempty"`
	MulticastFilteringPolicy            *GetWifiBroadcastDetailsMulticastFilteringPolicy `json:"multicastFilteringPolicy,omitempty"`
	MulticastToUnicastConversionEnabled bool                                             `json:"multicastToUnicastConversionEnabled"`
	ClientIsolationEnabled              bool                                             `json:"clientIsolationEnabled"`
	HideName                            bool                                             `json:"hideName"`
	// Indicates whether Unscheduled Automatic Power Save Delivery (U-APSD) is enabled
	UapsdEnabled                    bool                                                    `json:"uapsdEnabled"`
	BasicDataRateKbpsByFrequencyGHz *GetWifiBroadcastDetailsBasicDataRateKbpsByFrequencyGHz `json:"basicDataRateKbpsByFrequencyGHz,omitempty"`
	// Client connection filtering policy. Allow/restrict access to the WiFi network...
	ClientFilteringPolicy            *GetWifiBroadcastDetailsClientFilteringPolicy            `json:"clientFilteringPolicy,omitempty"`
	BlackoutScheduleConfiguration    *GetWifiBroadcastDetailsBlackoutScheduleConfiguration    `json:"blackoutScheduleConfiguration,omitempty"`
	BroadcastingFrequenciesGHz       []json.RawMessage                                        `json:"broadcastingFrequenciesGHz,omitempty"`
	HotspotConfiguration             *ClientAccess                                            `json:"hotspotConfiguration,omitempty"`
	MloEnabled                       bool                                                     `json:"mloEnabled,omitempty"`
	BandSteeringEnabled              bool                                                     `json:"bandSteeringEnabled,omitempty"`
	ArpProxyEnabled                  bool                                                     `json:"arpProxyEnabled,omitempty"`
	BssTransitionEnabled             bool                                                     `json:"bssTransitionEnabled,omitempty"`
	DtimPeriodByFrequencyGHzOverride *GetWifiBroadcastDetailsDtimPeriodByFrequencyGHzOverride `json:"dtimPeriodByFrequencyGHzOverride,omitempty"`
}

// GetWifiBroadcastDetailsMdnsProxyConfiguration represents a nested object structure.
type GetWifiBroadcastDetailsMdnsProxyConfiguration struct {
	Mode string `json:"mode"`
}

// GetWifiBroadcastDetailsSecurityConfigurationRadiusConfigurationNasId represents a nested object structure.
type GetWifiBroadcastDetailsSecurityConfigurationRadiusConfigurationNasId struct {
	Type   string `json:"type"`
	Source string `json:"source,omitempty"`
}

// GetWifiBroadcastDetailsMetadata represents a nested object structure.
type GetWifiBroadcastDetailsMetadata struct {
	Origin string `json:"origin"`
}

// GetWifiBroadcastDetailsBroadcastingDeviceFilter represents a nested object structure.
type GetWifiBroadcastDetailsBroadcastingDeviceFilter struct {
	Type string `json:"type"`
	// List of Access Point capable device IDs to which the WiFi broadcast applies.
	DeviceIds []json.RawMessage `json:"deviceIds,omitempty"`
}

// GetWifiBroadcastDetailsBasicDataRateKbpsByFrequencyGHz represents a nested object structure.
type GetWifiBroadcastDetailsBasicDataRateKbpsByFrequencyGHz struct {
	N5  int64 `json:"5"`
	N24 int64 `json:"2.4"`
}

// GetWifiBroadcastDetailsSecurityConfiguration represents a nested object structure.
type GetWifiBroadcastDetailsSecurityConfiguration struct {
	Type                string                                                           `json:"type"`
	RadiusConfiguration *GetWifiBroadcastDetailsSecurityConfigurationRadiusConfiguration `json:"radiusConfiguration,omitempty"`
}

// GetWifiBroadcastDetailsSecurityConfigurationRadiusConfiguration represents a nested object structure.
type GetWifiBroadcastDetailsSecurityConfigurationRadiusConfiguration struct {
	ProfileId                      string                                                                                         `json:"profileId"`
	NasId                          *GetWifiBroadcastDetailsSecurityConfigurationRadiusConfigurationNasId                          `json:"nasId"`
	MacAuthenticationConfiguration *GetWifiBroadcastDetailsSecurityConfigurationRadiusConfigurationMacAuthenticationConfiguration `json:"macAuthenticationConfiguration"`
}

// GetWifiBroadcastDetailsSecurityConfigurationRadiusConfigurationMacAuthenticationConfiguration represents a nested object structure.
type GetWifiBroadcastDetailsSecurityConfigurationRadiusConfigurationMacAuthenticationConfiguration struct {
	MacAddressFormat time.Time `json:"macAddressFormat"`
}

// GetWifiBroadcastDetailsBlackoutScheduleConfiguration represents a nested object structure.
type GetWifiBroadcastDetailsBlackoutScheduleConfiguration struct {
	Days []GetWifiBroadcastDetailsBlackoutScheduleConfigurationDays `json:"days"`
}

// GetWifiBroadcastDetailsDtimPeriodByFrequencyGHzOverride represents a nested object structure.
type GetWifiBroadcastDetailsDtimPeriodByFrequencyGHzOverride struct {
	N5  int64 `json:"5"`
	N6  int64 `json:"6"`
	N24 int64 `json:"2.4"`
}

// GetWifiBroadcastDetailsMulticastFilteringPolicy represents a nested object structure.
type GetWifiBroadcastDetailsMulticastFilteringPolicy struct {
	Action string `json:"action"`
	// List of multicast source MAC addresses allowed. Multicast traffic from gatewa...
	SourceMacAddressFilter []json.RawMessage `json:"sourceMacAddressFilter,omitempty"`
}

// GetWifiBroadcastDetailsClientFilteringPolicy represents a nested object structure.
type GetWifiBroadcastDetailsClientFilteringPolicy struct {
	Action           string            `json:"action"`
	MacAddressFilter []json.RawMessage `json:"macAddressFilter"`
}

// GetWifiBroadcastDetailsBlackoutScheduleConfigurationDays represents a nested object structure.
type GetWifiBroadcastDetailsBlackoutScheduleConfigurationDays struct {
	Type string `json:"type"`
	Day  string `json:"day"`
}
