// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Wifi Broadcasts
// Method: GET /v1/sites/{siteId}/wifi/broadcasts

package broadcasts

import (
	"encoding/json"
)

// ListWifiBroadcastsPathParams contains the path parameters for the ListWifiBroadcasts endpoint.
type ListWifiBroadcastsPathParams struct {
	SiteId string `json:"siteId"`
}

// ListWifiBroadcastsResponse contains the response body from the ListWifiBroadcasts endpoint.
type ListWifiBroadcastsResponse struct {
	PaginatedResponse
	Data []ListWifiBroadcastsData `json:"data"`
}

// ListWifiBroadcastsDataBroadcastingDeviceFilter represents a nested object structure.
type ListWifiBroadcastsDataBroadcastingDeviceFilter struct {
	Type string `json:"type"`
	// List of Access Point capable device IDs to which the WiFi broadcast applies.
	DeviceIds []json.RawMessage `json:"deviceIds,omitempty"`
}

// ListWifiBroadcastsDataMetadata represents a nested object structure.
type ListWifiBroadcastsDataMetadata struct {
	Origin string `json:"origin"`
}

// ListWifiBroadcastsData represents a nested object structure.
type ListWifiBroadcastsData struct {
	Type                  string                          `json:"type"`
	Id                    string                          `json:"id"`
	Name                  string                          `json:"name"`
	Enabled               bool                            `json:"enabled"`
	Metadata              *ListWifiBroadcastsDataMetadata `json:"metadata"`
	Network               *ClientAccess                   `json:"network,omitempty"`
	SecurityConfiguration *ClientAccess                   `json:"securityConfiguration"`
	// Defines the custom scope of devices that will broadcast this WiFi network. If...
	BroadcastingDeviceFilter   *ListWifiBroadcastsDataBroadcastingDeviceFilter `json:"broadcastingDeviceFilter,omitempty"`
	BroadcastingFrequenciesGHz []json.RawMessage                               `json:"broadcastingFrequenciesGHz,omitempty"`
	HotspotConfiguration       *ClientAccess                                   `json:"hotspotConfiguration,omitempty"`
}
