// Code generated by typegen. DO NOT EDIT.
// Endpoint: Update Wifi Broadcast
// Method: PUT /v1/sites/{siteId}/wifi/broadcasts/{wifiBroadcastId}

package broadcasts

import (
	"encoding/json"
	"fmt"
	"time"
)

// UpdateWifiBroadcastPathParams contains the path parameters for the UpdateWifiBroadcast endpoint.
type UpdateWifiBroadcastPathParams struct {
	WifiBroadcastId string `json:"wifiBroadcastId"`
	SiteId          string `json:"siteId"`
}

// UpdateWifiBroadcastRequestIotOptimized represents a nested object structure.
type UpdateWifiBroadcastRequestIotOptimized struct {
	Type                  string                                    `json:"type"`
	Name                  string                                    `json:"name"`
	Network               *ClientAccess                             `json:"network,omitempty"`
	Enabled               bool                                      `json:"enabled"`
	SecurityConfiguration *UpdateWifiBroadcastSecurityConfiguration `json:"securityConfiguration"`
	// Defines the custom scope of devices that will broadcast this WiFi network. If...
	BroadcastingDeviceFilter            *UpdateWifiBroadcastBroadcastingDeviceFilter `json:"broadcastingDeviceFilter,omitempty"`
	MdnsProxyConfiguration              *UpdateWifiBroadcastMdnsProxyConfiguration   `json:"mdnsProxyConfiguration,omitempty"`
	MulticastFilteringPolicy            *UpdateWifiBroadcastMulticastFilteringPolicy `json:"multicastFilteringPolicy,omitempty"`
	MulticastToUnicastConversionEnabled bool                                         `json:"multicastToUnicastConversionEnabled"`
	ClientIsolationEnabled              bool                                         `json:"clientIsolationEnabled"`
	HideName                            bool                                         `json:"hideName"`
	// Indicates whether Unscheduled Automatic Power Save Delivery (U-APSD) is enabled
	UapsdEnabled                    bool                                                `json:"uapsdEnabled"`
	BasicDataRateKbpsByFrequencyGHz *UpdateWifiBroadcastBasicDataRateKbpsByFrequencyGHz `json:"basicDataRateKbpsByFrequencyGHz,omitempty"`
	// Client connection filtering policy. Allow/restrict access to the WiFi network...
	ClientFilteringPolicy         *UpdateWifiBroadcastClientFilteringPolicy         `json:"clientFilteringPolicy,omitempty"`
	BlackoutScheduleConfiguration *UpdateWifiBroadcastBlackoutScheduleConfiguration `json:"blackoutScheduleConfiguration,omitempty"`
}

// UpdateWifiBroadcastRequestStandard represents a nested object structure.
type UpdateWifiBroadcastRequestStandard struct {
	Type                  string                                    `json:"type"`
	Name                  string                                    `json:"name"`
	Network               *ClientAccess                             `json:"network,omitempty"`
	Enabled               bool                                      `json:"enabled"`
	SecurityConfiguration *UpdateWifiBroadcastSecurityConfiguration `json:"securityConfiguration"`
	// Defines the custom scope of devices that will broadcast this WiFi network. If...
	BroadcastingDeviceFilter            *UpdateWifiBroadcastBroadcastingDeviceFilter `json:"broadcastingDeviceFilter,omitempty"`
	MdnsProxyConfiguration              *UpdateWifiBroadcastMdnsProxyConfiguration   `json:"mdnsProxyConfiguration,omitempty"`
	MulticastFilteringPolicy            *UpdateWifiBroadcastMulticastFilteringPolicy `json:"multicastFilteringPolicy,omitempty"`
	MulticastToUnicastConversionEnabled bool                                         `json:"multicastToUnicastConversionEnabled"`
	ClientIsolationEnabled              bool                                         `json:"clientIsolationEnabled"`
	HideName                            bool                                         `json:"hideName"`
	// Indicates whether Unscheduled Automatic Power Save Delivery (U-APSD) is enabled
	UapsdEnabled                    bool                                                `json:"uapsdEnabled"`
	BasicDataRateKbpsByFrequencyGHz *UpdateWifiBroadcastBasicDataRateKbpsByFrequencyGHz `json:"basicDataRateKbpsByFrequencyGHz,omitempty"`
	// Client connection filtering policy. Allow/restrict access to the WiFi network...
	ClientFilteringPolicy            *UpdateWifiBroadcastClientFilteringPolicy            `json:"clientFilteringPolicy,omitempty"`
	BlackoutScheduleConfiguration    *UpdateWifiBroadcastBlackoutScheduleConfiguration    `json:"blackoutScheduleConfiguration,omitempty"`
	BroadcastingFrequenciesGHz       []json.RawMessage                                    `json:"broadcastingFrequenciesGHz,omitempty"`
	HotspotConfiguration             *ClientAccess                                        `json:"hotspotConfiguration,omitempty"`
	MloEnabled                       bool                                                 `json:"mloEnabled,omitempty"`
	BandSteeringEnabled              bool                                                 `json:"bandSteeringEnabled,omitempty"`
	ArpProxyEnabled                  bool                                                 `json:"arpProxyEnabled,omitempty"`
	BssTransitionEnabled             bool                                                 `json:"bssTransitionEnabled,omitempty"`
	DtimPeriodByFrequencyGHzOverride *UpdateWifiBroadcastDtimPeriodByFrequencyGHzOverride `json:"dtimPeriodByFrequencyGHzOverride,omitempty"`
}

// UpdateWifiBroadcastResponseIotOptimized represents a nested object structure.
type UpdateWifiBroadcastResponseIotOptimized struct {
	Type                  string                                    `json:"type"`
	Id                    string                                    `json:"id"`
	Name                  string                                    `json:"name"`
	Metadata              *UpdateWifiBroadcastMetadata              `json:"metadata"`
	Enabled               bool                                      `json:"enabled"`
	Network               *ClientAccess                             `json:"network,omitempty"`
	SecurityConfiguration *UpdateWifiBroadcastSecurityConfiguration `json:"securityConfiguration"`
	// Defines the custom scope of devices that will broadcast this WiFi network. If...
	BroadcastingDeviceFilter            *UpdateWifiBroadcastBroadcastingDeviceFilter `json:"broadcastingDeviceFilter,omitempty"`
	MdnsProxyConfiguration              *UpdateWifiBroadcastMdnsProxyConfiguration   `json:"mdnsProxyConfiguration,omitempty"`
	MulticastFilteringPolicy            *UpdateWifiBroadcastMulticastFilteringPolicy `json:"multicastFilteringPolicy,omitempty"`
	MulticastToUnicastConversionEnabled bool                                         `json:"multicastToUnicastConversionEnabled"`
	ClientIsolationEnabled              bool                                         `json:"clientIsolationEnabled"`
	HideName                            bool                                         `json:"hideName"`
	// Indicates whether Unscheduled Automatic Power Save Delivery (U-APSD) is enabled
	UapsdEnabled                    bool                                                `json:"uapsdEnabled"`
	BasicDataRateKbpsByFrequencyGHz *UpdateWifiBroadcastBasicDataRateKbpsByFrequencyGHz `json:"basicDataRateKbpsByFrequencyGHz,omitempty"`
	// Client connection filtering policy. Allow/restrict access to the WiFi network...
	ClientFilteringPolicy            *UpdateWifiBroadcastClientFilteringPolicy            `json:"clientFilteringPolicy,omitempty"`
	BlackoutScheduleConfiguration    *UpdateWifiBroadcastBlackoutScheduleConfiguration    `json:"blackoutScheduleConfiguration,omitempty"`
	BroadcastingFrequenciesGHz       []json.RawMessage                                    `json:"broadcastingFrequenciesGHz,omitempty"`
	HotspotConfiguration             *ClientAccess                                        `json:"hotspotConfiguration,omitempty"`
	MloEnabled                       bool                                                 `json:"mloEnabled,omitempty"`
	BandSteeringEnabled              bool                                                 `json:"bandSteeringEnabled,omitempty"`
	ArpProxyEnabled                  bool                                                 `json:"arpProxyEnabled,omitempty"`
	BssTransitionEnabled             bool                                                 `json:"bssTransitionEnabled,omitempty"`
	DtimPeriodByFrequencyGHzOverride *UpdateWifiBroadcastDtimPeriodByFrequencyGHzOverride `json:"dtimPeriodByFrequencyGHzOverride,omitempty"`
}

// UpdateWifiBroadcastResponseStandard represents a nested object structure.
type UpdateWifiBroadcastResponseStandard struct {
	Type                  string                                    `json:"type"`
	Id                    string                                    `json:"id"`
	Name                  string                                    `json:"name"`
	Metadata              *UpdateWifiBroadcastMetadata              `json:"metadata"`
	Enabled               bool                                      `json:"enabled"`
	Network               *ClientAccess                             `json:"network,omitempty"`
	SecurityConfiguration *UpdateWifiBroadcastSecurityConfiguration `json:"securityConfiguration"`
	// Defines the custom scope of devices that will broadcast this WiFi network. If...
	BroadcastingDeviceFilter            *UpdateWifiBroadcastBroadcastingDeviceFilter `json:"broadcastingDeviceFilter,omitempty"`
	MdnsProxyConfiguration              *UpdateWifiBroadcastMdnsProxyConfiguration   `json:"mdnsProxyConfiguration,omitempty"`
	MulticastFilteringPolicy            *UpdateWifiBroadcastMulticastFilteringPolicy `json:"multicastFilteringPolicy,omitempty"`
	MulticastToUnicastConversionEnabled bool                                         `json:"multicastToUnicastConversionEnabled"`
	ClientIsolationEnabled              bool                                         `json:"clientIsolationEnabled"`
	HideName                            bool                                         `json:"hideName"`
	// Indicates whether Unscheduled Automatic Power Save Delivery (U-APSD) is enabled
	UapsdEnabled                    bool                                                `json:"uapsdEnabled"`
	BasicDataRateKbpsByFrequencyGHz *UpdateWifiBroadcastBasicDataRateKbpsByFrequencyGHz `json:"basicDataRateKbpsByFrequencyGHz,omitempty"`
	// Client connection filtering policy. Allow/restrict access to the WiFi network...
	ClientFilteringPolicy            *UpdateWifiBroadcastClientFilteringPolicy            `json:"clientFilteringPolicy,omitempty"`
	BlackoutScheduleConfiguration    *UpdateWifiBroadcastBlackoutScheduleConfiguration    `json:"blackoutScheduleConfiguration,omitempty"`
	BroadcastingFrequenciesGHz       []json.RawMessage                                    `json:"broadcastingFrequenciesGHz,omitempty"`
	HotspotConfiguration             *ClientAccess                                        `json:"hotspotConfiguration,omitempty"`
	MloEnabled                       bool                                                 `json:"mloEnabled,omitempty"`
	BandSteeringEnabled              bool                                                 `json:"bandSteeringEnabled,omitempty"`
	ArpProxyEnabled                  bool                                                 `json:"arpProxyEnabled,omitempty"`
	BssTransitionEnabled             bool                                                 `json:"bssTransitionEnabled,omitempty"`
	DtimPeriodByFrequencyGHzOverride *UpdateWifiBroadcastDtimPeriodByFrequencyGHzOverride `json:"dtimPeriodByFrequencyGHzOverride,omitempty"`
}

// UpdateWifiBroadcastDtimPeriodByFrequencyGHzOverride represents a nested object structure.
type UpdateWifiBroadcastDtimPeriodByFrequencyGHzOverride struct {
	N5  int64 `json:"5"`
	N6  int64 `json:"6"`
	N24 int64 `json:"2.4"`
}

// UpdateWifiBroadcastSecurityConfigurationRadiusConfiguration represents a nested object structure.
type UpdateWifiBroadcastSecurityConfigurationRadiusConfiguration struct {
	ProfileId                      string                                                                                     `json:"profileId"`
	NasId                          *UpdateWifiBroadcastSecurityConfigurationRadiusConfigurationNasId                          `json:"nasId"`
	MacAuthenticationConfiguration *UpdateWifiBroadcastSecurityConfigurationRadiusConfigurationMacAuthenticationConfiguration `json:"macAuthenticationConfiguration"`
}

// UpdateWifiBroadcastClientFilteringPolicy represents a nested object structure.
type UpdateWifiBroadcastClientFilteringPolicy struct {
	Action           string            `json:"action"`
	MacAddressFilter []json.RawMessage `json:"macAddressFilter"`
}

// UpdateWifiBroadcastSecurityConfigurationRadiusConfigurationMacAuthenticationConfiguration represents a nested object structure.
type UpdateWifiBroadcastSecurityConfigurationRadiusConfigurationMacAuthenticationConfiguration struct {
	MacAddressFormat time.Time `json:"macAddressFormat"`
}

// UpdateWifiBroadcastSecurityConfiguration represents a nested object structure.
type UpdateWifiBroadcastSecurityConfiguration struct {
	Type                string                                                       `json:"type"`
	RadiusConfiguration *UpdateWifiBroadcastSecurityConfigurationRadiusConfiguration `json:"radiusConfiguration,omitempty"`
}

// UpdateWifiBroadcastMdnsProxyConfiguration represents a nested object structure.
type UpdateWifiBroadcastMdnsProxyConfiguration struct {
	Mode string `json:"mode"`
}

// UpdateWifiBroadcastBroadcastingDeviceFilter represents a nested object structure.
type UpdateWifiBroadcastBroadcastingDeviceFilter struct {
	Type string `json:"type"`
	// List of Access Point capable device IDs to which the WiFi broadcast applies.
	DeviceIds []json.RawMessage `json:"deviceIds,omitempty"`
}

// UpdateWifiBroadcastBlackoutScheduleConfigurationDays represents a nested object structure.
type UpdateWifiBroadcastBlackoutScheduleConfigurationDays struct {
	Type string `json:"type"`
	Day  string `json:"day"`
}

// UpdateWifiBroadcastMulticastFilteringPolicy represents a nested object structure.
type UpdateWifiBroadcastMulticastFilteringPolicy struct {
	Action string `json:"action"`
	// List of multicast source MAC addresses allowed. Multicast traffic from gatewa...
	SourceMacAddressFilter []json.RawMessage `json:"sourceMacAddressFilter,omitempty"`
}

// UpdateWifiBroadcastSecurityConfigurationRadiusConfigurationNasId represents a nested object structure.
type UpdateWifiBroadcastSecurityConfigurationRadiusConfigurationNasId struct {
	Type   string `json:"type"`
	Source string `json:"source,omitempty"`
}

// UpdateWifiBroadcastBasicDataRateKbpsByFrequencyGHz represents a nested object structure.
type UpdateWifiBroadcastBasicDataRateKbpsByFrequencyGHz struct {
	N5  int64 `json:"5"`
	N24 int64 `json:"2.4"`
}

// UpdateWifiBroadcastMetadata represents a nested object structure.
type UpdateWifiBroadcastMetadata struct {
	Origin string `json:"origin"`
}

// UpdateWifiBroadcastBlackoutScheduleConfiguration represents a nested object structure.
type UpdateWifiBroadcastBlackoutScheduleConfiguration struct {
	Days []UpdateWifiBroadcastBlackoutScheduleConfigurationDays `json:"days"`
}

// UpdateWifiBroadcastType represents the type enum values.
type UpdateWifiBroadcastType string

const (
	UpdateWifiBroadcastTypeStandard     UpdateWifiBroadcastType = "STANDARD"
	UpdateWifiBroadcastTypeIotOptimized UpdateWifiBroadcastType = "IOT_OPTIMIZED"
)

type UpdateWifiBroadcastVariantEnvelope struct {
	Type string `json:"type"`
}

// DecodeUpdateWifiBroadcastResponse decodes a variant response based on the type field.
func DecodeUpdateWifiBroadcastResponse(data []byte) (any, error) {
	var env UpdateWifiBroadcastVariantEnvelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}

	switch env.Type {
	case "IOT_OPTIMIZED":
		var out UpdateWifiBroadcastResponseIotOptimized
		return &out, json.Unmarshal(data, &out)
	case "STANDARD":
		var out UpdateWifiBroadcastResponseStandard
		return &out, json.Unmarshal(data, &out)
	default:
		return nil, fmt.Errorf("unknown type value: %s", env.Type)
	}
}
