// Code generated by clientgen. DO NOT EDIT.

package device_tags

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// DeviceTags provides access to the DeviceTags API.
type DeviceTags struct {
	client *http.Client
}

// NewDeviceTags creates a new DeviceTags instance.
func NewDeviceTags(client *http.Client) *DeviceTags {
	return &DeviceTags{
		client: client,
	}
}

// ListDeviceTags calls the ListDeviceTags endpoint.
// GET /v1/sites/{siteId}/device-tags
func (c *DeviceTags) ListDeviceTags(ctx context.Context, siteId string) (*ListDeviceTagsResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/device-tags", siteId)
	var result ListDeviceTagsResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
