// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Device Tags
// Method: GET /v1/sites/{siteId}/device-tags

package device_tags

import (
	"encoding/json"
)

// ListDeviceTagsPathParams contains the path parameters for the ListDeviceTags endpoint.
type ListDeviceTagsPathParams struct {
	SiteId string `json:"siteId"`
}

// ListDeviceTagsResponse contains the response body from the ListDeviceTags endpoint.
type ListDeviceTagsResponse struct {
	PaginatedResponse
	Data []ListDeviceTagsData `json:"data"`
}

// ListDeviceTagsData represents a nested object structure.
type ListDeviceTagsData struct {
	Id        string                      `json:"id"`
	Name      string                      `json:"name"`
	DeviceIds []json.RawMessage           `json:"deviceIds"`
	Metadata  *ListDeviceTagsDataMetadata `json:"metadata"`
}

// ListDeviceTagsDataMetadata represents a nested object structure.
type ListDeviceTagsDataMetadata struct {
	Origin string `json:"origin"`
}
