// Code generated by clientgen. DO NOT EDIT.

package countries

import (
	"context"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// Countries provides access to the Countries API.
type Countries struct {
	client *http.Client
}

// NewCountries creates a new Countries instance.
func NewCountries(client *http.Client) *Countries {
	return &Countries{
		client: client,
	}
}

// ListCountries calls the ListCountries endpoint.
// GET /v1/countries
func (c *Countries) ListCountries(ctx context.Context) (*ListCountriesResponse, error) {
	path := "/v1/countries"
	var result ListCountriesResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
