// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Countries
// Method: GET /v1/countries

package countries

// ListCountriesResponse contains the response body from the ListCountries endpoint.
type ListCountriesResponse struct {
	PaginatedResponse
	Data []ListCountriesData `json:"data"`
}

// ListCountriesData represents a nested object structure.
type ListCountriesData struct {
	// The country code in ISO 3166-1 alpha-2 format.
	Code string `json:"code"`
	// The country name.
	Name string `json:"name"`
}
