// Code generated by typegen. DO NOT EDIT.
// Endpoint: Create Traffic Matching List
// Method: POST /v1/sites/{siteId}/traffic-matching-lists

package traffic_matching_lists

// CreateTrafficMatchingListPathParams contains the path parameters for the CreateTrafficMatchingList endpoint.
type CreateTrafficMatchingListPathParams struct {
	SiteId string `json:"siteId"`
}

// CreateTrafficMatchingListRequest contains the request body for the CreateTrafficMatchingList endpoint.
type CreateTrafficMatchingListRequest struct {
	Type  string                           `json:"type"`
	Name  string                           `json:"name"`
	Items []CreateTrafficMatchingListItems `json:"items,omitempty"`
}

// CreateTrafficMatchingListResponse contains the response body from the CreateTrafficMatchingList endpoint.
type CreateTrafficMatchingListResponse struct {
	Type  string                           `json:"type"`
	Id    string                           `json:"id"`
	Name  string                           `json:"name"`
	Items []CreateTrafficMatchingListItems `json:"items,omitempty"`
}

// CreateTrafficMatchingListItems represents a nested object structure.
type CreateTrafficMatchingListItems struct {
	Type string `json:"type"`
	// Port number
	Value int64 `json:"value,omitempty"`
}

// CreateTrafficMatchingListType represents the type enum values.
type CreateTrafficMatchingListType string

const (
	CreateTrafficMatchingListTypePorts         CreateTrafficMatchingListType = "PORTS"
	CreateTrafficMatchingListTypeIpv4Addresses CreateTrafficMatchingListType = "IPV4_ADDRESSES"
	CreateTrafficMatchingListTypeIpv6Addresses CreateTrafficMatchingListType = "IPV6_ADDRESSES"
)
