// Code generated by typegen. DO NOT EDIT.
// Endpoint: Create Traffic Matching List
// Method: POST /v1/sites/{siteId}/traffic-matching-lists

package traffic_matching_lists

import (
	"encoding/json"
	"fmt"
)

// CreateTrafficMatchingListPathParams contains the path parameters for the CreateTrafficMatchingList endpoint.
type CreateTrafficMatchingListPathParams struct {
	SiteId string `json:"siteId"`
}

// CreateTrafficMatchingListRequestIpv4Addresses represents a nested object structure.
type CreateTrafficMatchingListRequestIpv4Addresses struct {
	Type  string                           `json:"type"`
	Name  string                           `json:"name"`
	Items []CreateTrafficMatchingListItems `json:"items,omitempty"`
}

// CreateTrafficMatchingListRequestIpv6Addresses represents a nested object structure.
type CreateTrafficMatchingListRequestIpv6Addresses struct {
	Type  string                           `json:"type"`
	Name  string                           `json:"name"`
	Items []CreateTrafficMatchingListItems `json:"items,omitempty"`
}

// CreateTrafficMatchingListRequestPorts represents a nested object structure.
type CreateTrafficMatchingListRequestPorts struct {
	Type  string                           `json:"type"`
	Name  string                           `json:"name"`
	Items []CreateTrafficMatchingListItems `json:"items,omitempty"`
}

// CreateTrafficMatchingListResponseIpv4Addresses represents a nested object structure.
type CreateTrafficMatchingListResponseIpv4Addresses struct {
	Type  string                           `json:"type"`
	Id    string                           `json:"id"`
	Name  string                           `json:"name"`
	Items []CreateTrafficMatchingListItems `json:"items,omitempty"`
}

// CreateTrafficMatchingListResponseIpv6Addresses represents a nested object structure.
type CreateTrafficMatchingListResponseIpv6Addresses struct {
	Type  string                           `json:"type"`
	Id    string                           `json:"id"`
	Name  string                           `json:"name"`
	Items []CreateTrafficMatchingListItems `json:"items,omitempty"`
}

// CreateTrafficMatchingListResponsePorts represents a nested object structure.
type CreateTrafficMatchingListResponsePorts struct {
	Type  string                           `json:"type"`
	Id    string                           `json:"id"`
	Name  string                           `json:"name"`
	Items []CreateTrafficMatchingListItems `json:"items,omitempty"`
}

// CreateTrafficMatchingListItems represents a nested object structure.
type CreateTrafficMatchingListItems struct {
	Type string `json:"type"`
	// Port number
	Value int64 `json:"value,omitempty"`
}

// CreateTrafficMatchingListType represents the type enum values.
type CreateTrafficMatchingListType string

const (
	CreateTrafficMatchingListTypePorts         CreateTrafficMatchingListType = "PORTS"
	CreateTrafficMatchingListTypeIpv4Addresses CreateTrafficMatchingListType = "IPV4_ADDRESSES"
	CreateTrafficMatchingListTypeIpv6Addresses CreateTrafficMatchingListType = "IPV6_ADDRESSES"
)

type CreateTrafficMatchingListVariantEnvelope struct {
	Type string `json:"type"`
}

// DecodeCreateTrafficMatchingListResponse decodes a variant response based on the type field.
func DecodeCreateTrafficMatchingListResponse(data []byte) (any, error) {
	var env CreateTrafficMatchingListVariantEnvelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}

	switch env.Type {
	case "IPV4_ADDRESSES":
		var out CreateTrafficMatchingListResponseIpv4Addresses
		return &out, json.Unmarshal(data, &out)
	case "IPV6_ADDRESSES":
		var out CreateTrafficMatchingListResponseIpv6Addresses
		return &out, json.Unmarshal(data, &out)
	case "PORTS":
		var out CreateTrafficMatchingListResponsePorts
		return &out, json.Unmarshal(data, &out)
	default:
		return nil, fmt.Errorf("unknown type value: %s", env.Type)
	}
}
