// Code generated by typegen. DO NOT EDIT.
// Endpoint: Delete Traffic Matching List
// Method: DELETE /v1/sites/{siteId}/traffic-matching-lists/{trafficMatchingListId}

package traffic_matching_lists

// DeleteTrafficMatchingListPathParams contains the path parameters for the DeleteTrafficMatchingList endpoint.
type DeleteTrafficMatchingListPathParams struct {
	TrafficMatchingListId string `json:"trafficMatchingListId"`
	SiteId                string `json:"siteId"`
}

// DeleteTrafficMatchingListResponse represents the API response for Delete Traffic Matching List.
type DeleteTrafficMatchingListResponse struct{}
