// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Traffic Matching List
// Method: GET /v1/sites/{siteId}/traffic-matching-lists/{trafficMatchingListId}

package traffic_matching_lists

// GetTrafficMatchingListPathParams contains the path parameters for the GetTrafficMatchingList endpoint.
type GetTrafficMatchingListPathParams struct {
	TrafficMatchingListId string `json:"trafficMatchingListId"`
	SiteId                string `json:"siteId"`
}

// GetTrafficMatchingListResponse contains the response body from the GetTrafficMatchingList endpoint.
type GetTrafficMatchingListResponse struct {
	Type  string                        `json:"type"`
	Id    string                        `json:"id"`
	Name  string                        `json:"name"`
	Items []GetTrafficMatchingListItems `json:"items,omitempty"`
}

// GetTrafficMatchingListItems represents a nested object structure.
type GetTrafficMatchingListItems struct {
	Type string `json:"type"`
	// Port number
	Value int64 `json:"value,omitempty"`
}
