// Code generated by typegen. DO NOT EDIT.
// Endpoint: Get Traffic Matching List
// Method: GET /v1/sites/{siteId}/traffic-matching-lists/{trafficMatchingListId}

package traffic_matching_lists

import (
	"encoding/json"
	"fmt"
)

// GetTrafficMatchingListPathParams contains the path parameters for the GetTrafficMatchingList endpoint.
type GetTrafficMatchingListPathParams struct {
	TrafficMatchingListId string `json:"trafficMatchingListId"`
	SiteId                string `json:"siteId"`
}

// GetTrafficMatchingListResponseIpv4Addresses represents a nested object structure.
type GetTrafficMatchingListResponseIpv4Addresses struct {
	Type  string                        `json:"type"`
	Id    string                        `json:"id"`
	Name  string                        `json:"name"`
	Items []GetTrafficMatchingListItems `json:"items,omitempty"`
}

// GetTrafficMatchingListResponseIpv6Addresses represents a nested object structure.
type GetTrafficMatchingListResponseIpv6Addresses struct {
	Type  string                        `json:"type"`
	Id    string                        `json:"id"`
	Name  string                        `json:"name"`
	Items []GetTrafficMatchingListItems `json:"items,omitempty"`
}

// GetTrafficMatchingListResponsePorts represents a nested object structure.
type GetTrafficMatchingListResponsePorts struct {
	Type  string                        `json:"type"`
	Id    string                        `json:"id"`
	Name  string                        `json:"name"`
	Items []GetTrafficMatchingListItems `json:"items,omitempty"`
}

// GetTrafficMatchingListItems represents a nested object structure.
type GetTrafficMatchingListItems struct {
	Type string `json:"type"`
	// Port number
	Value int64 `json:"value,omitempty"`
}

type GetTrafficMatchingListVariantEnvelope struct {
	Type string `json:"type"`
}

// DecodeGetTrafficMatchingListResponse decodes a variant response based on the type field.
func DecodeGetTrafficMatchingListResponse(data []byte) (any, error) {
	var env GetTrafficMatchingListVariantEnvelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}

	switch env.Type {
	case "IPV4_ADDRESSES":
		var out GetTrafficMatchingListResponseIpv4Addresses
		return &out, json.Unmarshal(data, &out)
	case "IPV6_ADDRESSES":
		var out GetTrafficMatchingListResponseIpv6Addresses
		return &out, json.Unmarshal(data, &out)
	case "PORTS":
		var out GetTrafficMatchingListResponsePorts
		return &out, json.Unmarshal(data, &out)
	default:
		return nil, fmt.Errorf("unknown type value: %s", env.Type)
	}
}
