// Code generated by typegen. DO NOT EDIT.
// Endpoint: List Traffic Matching Lists
// Method: GET /v1/sites/{siteId}/traffic-matching-lists

package traffic_matching_lists

// ListTrafficMatchingListsPathParams contains the path parameters for the ListTrafficMatchingLists endpoint.
type ListTrafficMatchingListsPathParams struct {
	SiteId string `json:"siteId"`
}

// ListTrafficMatchingListsResponse contains the response body from the ListTrafficMatchingLists endpoint.
type ListTrafficMatchingListsResponse struct {
	PaginatedResponse
	Data []ListTrafficMatchingListsData `json:"data"`
}

// ListTrafficMatchingListsData represents a nested object structure.
type ListTrafficMatchingListsData struct {
	Type  string                              `json:"type"`
	Id    string                              `json:"id"`
	Name  string                              `json:"name"`
	Items []ListTrafficMatchingListsDataItems `json:"items,omitempty"`
}

// ListTrafficMatchingListsDataItems represents a nested object structure.
type ListTrafficMatchingListsDataItems struct {
	Type string `json:"type"`
	// Port number
	Value int64 `json:"value,omitempty"`
}
