// Code generated by clientgen. DO NOT EDIT.

package traffic_matching_lists

import (
	"context"
	"fmt"

	"github.com/ilmax/unifi-client-go/internal/http"
)

// TrafficMatchingLists provides access to the TrafficMatchingLists API.
type TrafficMatchingLists struct {
	client *http.Client
}

// NewTrafficMatchingLists creates a new TrafficMatchingLists instance.
func NewTrafficMatchingLists(client *http.Client) *TrafficMatchingLists {
	return &TrafficMatchingLists{
		client: client,
	}
}

// CreateTrafficMatchingList calls the CreateTrafficMatchingList endpoint.
// POST /v1/sites/{siteId}/traffic-matching-lists
func (c *TrafficMatchingLists) CreateTrafficMatchingList(ctx context.Context, siteId string, req any) (any, error) {
	path := fmt.Sprintf("/v1/sites/%s/traffic-matching-lists", siteId)
	var result any
	if err := c.client.Post(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// DeleteTrafficMatchingList calls the DeleteTrafficMatchingList endpoint.
// DELETE /v1/sites/{siteId}/traffic-matching-lists/{trafficMatchingListId}
func (c *TrafficMatchingLists) DeleteTrafficMatchingList(ctx context.Context, trafficMatchingListId string, siteId string) (*DeleteTrafficMatchingListResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/traffic-matching-lists/%s", trafficMatchingListId, siteId)
	var result DeleteTrafficMatchingListResponse
	if err := c.client.Delete(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListTrafficMatchingList calls the GetTrafficMatchingList endpoint.
// GET /v1/sites/{siteId}/traffic-matching-lists/{trafficMatchingListId}
func (c *TrafficMatchingLists) ListTrafficMatchingList(ctx context.Context, trafficMatchingListId string, siteId string) (any, error) {
	path := fmt.Sprintf("/v1/sites/%s/traffic-matching-lists/%s", trafficMatchingListId, siteId)
	var result any
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// ListTrafficMatchingLists calls the ListTrafficMatchingLists endpoint.
// GET /v1/sites/{siteId}/traffic-matching-lists
func (c *TrafficMatchingLists) ListTrafficMatchingLists(ctx context.Context, siteId string) (*ListTrafficMatchingListsResponse, error) {
	path := fmt.Sprintf("/v1/sites/%s/traffic-matching-lists", siteId)
	var result ListTrafficMatchingListsResponse
	if err := c.client.Get(ctx, path, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateTrafficMatchingList calls the UpdateTrafficMatchingList endpoint.
// PUT /v1/sites/{siteId}/traffic-matching-lists/{trafficMatchingListId}
func (c *TrafficMatchingLists) UpdateTrafficMatchingList(ctx context.Context, trafficMatchingListId string, siteId string, req any) (any, error) {
	path := fmt.Sprintf("/v1/sites/%s/traffic-matching-lists/%s", trafficMatchingListId, siteId)
	var result any
	if err := c.client.Put(ctx, path, req, &result); err != nil {
		return nil, err
	}
	return result, nil
}
