// Code generated by typegen. DO NOT EDIT.
// Endpoint: Update Traffic Matching List
// Method: PUT /v1/sites/{siteId}/traffic-matching-lists/{trafficMatchingListId}

package traffic_matching_lists

import (
	"encoding/json"
	"fmt"
)

// UpdateTrafficMatchingListPathParams contains the path parameters for the UpdateTrafficMatchingList endpoint.
type UpdateTrafficMatchingListPathParams struct {
	TrafficMatchingListId string `json:"trafficMatchingListId"`
	SiteId                string `json:"siteId"`
}

// UpdateTrafficMatchingListRequestIpv4Addresses represents a nested object structure.
type UpdateTrafficMatchingListRequestIpv4Addresses struct {
	Type  string                           `json:"type"`
	Name  string                           `json:"name"`
	Items []UpdateTrafficMatchingListItems `json:"items,omitempty"`
}

// UpdateTrafficMatchingListRequestIpv6Addresses represents a nested object structure.
type UpdateTrafficMatchingListRequestIpv6Addresses struct {
	Type  string                           `json:"type"`
	Name  string                           `json:"name"`
	Items []UpdateTrafficMatchingListItems `json:"items,omitempty"`
}

// UpdateTrafficMatchingListRequestPorts represents a nested object structure.
type UpdateTrafficMatchingListRequestPorts struct {
	Type  string                           `json:"type"`
	Name  string                           `json:"name"`
	Items []UpdateTrafficMatchingListItems `json:"items,omitempty"`
}

// UpdateTrafficMatchingListResponseIpv4Addresses represents a nested object structure.
type UpdateTrafficMatchingListResponseIpv4Addresses struct {
	Type  string                           `json:"type"`
	Id    string                           `json:"id"`
	Name  string                           `json:"name"`
	Items []UpdateTrafficMatchingListItems `json:"items,omitempty"`
}

// UpdateTrafficMatchingListResponseIpv6Addresses represents a nested object structure.
type UpdateTrafficMatchingListResponseIpv6Addresses struct {
	Type  string                           `json:"type"`
	Id    string                           `json:"id"`
	Name  string                           `json:"name"`
	Items []UpdateTrafficMatchingListItems `json:"items,omitempty"`
}

// UpdateTrafficMatchingListResponsePorts represents a nested object structure.
type UpdateTrafficMatchingListResponsePorts struct {
	Type  string                           `json:"type"`
	Id    string                           `json:"id"`
	Name  string                           `json:"name"`
	Items []UpdateTrafficMatchingListItems `json:"items,omitempty"`
}

// UpdateTrafficMatchingListItems represents a nested object structure.
type UpdateTrafficMatchingListItems struct {
	Type string `json:"type"`
	// Port number
	Value int64 `json:"value,omitempty"`
}

// UpdateTrafficMatchingListType represents the type enum values.
type UpdateTrafficMatchingListType string

const (
	UpdateTrafficMatchingListTypePorts         UpdateTrafficMatchingListType = "PORTS"
	UpdateTrafficMatchingListTypeIpv4Addresses UpdateTrafficMatchingListType = "IPV4_ADDRESSES"
	UpdateTrafficMatchingListTypeIpv6Addresses UpdateTrafficMatchingListType = "IPV6_ADDRESSES"
)

type UpdateTrafficMatchingListVariantEnvelope struct {
	Type string `json:"type"`
}

// DecodeUpdateTrafficMatchingListResponse decodes a variant response based on the type field.
func DecodeUpdateTrafficMatchingListResponse(data []byte) (any, error) {
	var env UpdateTrafficMatchingListVariantEnvelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}

	switch env.Type {
	case "IPV4_ADDRESSES":
		var out UpdateTrafficMatchingListResponseIpv4Addresses
		return &out, json.Unmarshal(data, &out)
	case "IPV6_ADDRESSES":
		var out UpdateTrafficMatchingListResponseIpv6Addresses
		return &out, json.Unmarshal(data, &out)
	case "PORTS":
		var out UpdateTrafficMatchingListResponsePorts
		return &out, json.Unmarshal(data, &out)
	default:
		return nil, fmt.Errorf("unknown type value: %s", env.Type)
	}
}
