// Code generated by typegen. DO NOT EDIT.
// Endpoint: Update Traffic Matching List
// Method: PUT /v1/sites/{siteId}/traffic-matching-lists/{trafficMatchingListId}

package traffic_matching_lists

// UpdateTrafficMatchingListPathParams contains the path parameters for the UpdateTrafficMatchingList endpoint.
type UpdateTrafficMatchingListPathParams struct {
	TrafficMatchingListId string `json:"trafficMatchingListId"`
	SiteId                string `json:"siteId"`
}

// UpdateTrafficMatchingListRequest contains the request body for the UpdateTrafficMatchingList endpoint.
type UpdateTrafficMatchingListRequest struct {
	Type  string                           `json:"type"`
	Name  string                           `json:"name"`
	Items []UpdateTrafficMatchingListItems `json:"items,omitempty"`
}

// UpdateTrafficMatchingListResponse contains the response body from the UpdateTrafficMatchingList endpoint.
type UpdateTrafficMatchingListResponse struct {
	Type  string                           `json:"type"`
	Id    string                           `json:"id"`
	Name  string                           `json:"name"`
	Items []UpdateTrafficMatchingListItems `json:"items,omitempty"`
}

// UpdateTrafficMatchingListItems represents a nested object structure.
type UpdateTrafficMatchingListItems struct {
	Type string `json:"type"`
	// Port number
	Value int64 `json:"value,omitempty"`
}

// UpdateTrafficMatchingListType represents the type enum values.
type UpdateTrafficMatchingListType string

const (
	UpdateTrafficMatchingListTypePorts         UpdateTrafficMatchingListType = "PORTS"
	UpdateTrafficMatchingListTypeIpv4Addresses UpdateTrafficMatchingListType = "IPV4_ADDRESSES"
	UpdateTrafficMatchingListTypeIpv6Addresses UpdateTrafficMatchingListType = "IPV6_ADDRESSES"
)
